(function(root){'use strict';
 function mount(id,c){const M=NamdongMath,s=c.state.boat,{board,controls,confirm}=c;let destroyGame=()=>{},pauseGame=()=>{},dead=false;
  board.className='board moon-board';
  function scale(){board.className='board central-scale-board';board.innerHTML='<div class="central-scale-conditions"><span>축척<strong>1 : 5,000</strong></span><span>지도 속 항로<strong>9cm</strong></span></div><div class="central-map-space">'+CentralRouteMap.markup()+'</div><div class="central-scale-caption">원본 지도에서 잰 항로 길이예요. 화면에서는 확대·축소되어 보여요.<br>공개 지도 좌표를 바탕으로 그린 학습용 지도 · © OpenStreetMap contributors</div>';
   controls.classList.add('central-scale-aside');controls.innerHTML='<small>MISSION 01 · 축척</small><h2>토끼섬까지 얼마나 갈까요?</h2><p class="central-scale-question">표시된 항로의<br>실제 거리는 몇 m일까요?</p><div class="central-scale-answer"><input id="scaleAnswer" type="text" inputmode="decimal" autocomplete="off" aria-label="실제 거리 정답"><span>m</span></div><button id="scaleHint">생각 도우미</button><button id="routeDetail">지도 크게 보기</button><small>선착장에서 다리를 지나<br>토끼섬 옆 물길까지 가요.</small>';
   controls.querySelector('#routeDetail').onclick=CentralRouteMap.open;controls.querySelector('#scaleHint').onclick=()=>c.feedback('지도 1cm는 실제 5,000cm, 즉 50m예요. 9cm라면 50 × 9를 계산해요.');confirm.textContent='거리 확인하고 탑승 →';confirm.hidden=false;confirm.onclick=()=>{if(!M.exact(controls.querySelector('#scaleAnswer').value,450)){c.feedback('단위를 확인해 봐요. 5,000cm = 50m이고, 항로는 지도에서 9cm예요.','bad');c.tone(false);return;}s.version=2;s.scale=450;c.persist();start();};controls.querySelector('#scaleAnswer').onkeydown=e=>{if(e.key==='Enter')confirm.click();};c.feedback('축척과 지도 속 항로의 길이를 함께 살펴보세요.');
  }
  function start(){destroyGame();if(dead)return;board.className='board moon-board';controls.classList.remove('central-scale-aside');   confirm.hidden=true;board.innerHTML='<div class="boat-view"></div><div class="boat-hud"><span id="boatTravel">0 / 약 450m</span><span id="boatLocation" class="location-readout">이스트보트하우스</span><button id="viewMode">탑승 시점으로</button></div><div class="lane-guide"></div><div class="boat-landmark" hidden><strong></strong><p></p></div><button class="central-mini-map" aria-label="항로 지도 크게 보기">'+CentralRouteMap.markup(true)+'<span>현재 위치 · 지도 보기</span></button><div class="boat-message" role="status" hidden></div><div class="boat-inputs"><button id="steerLeft" aria-label="문보트 왼쪽으로 이동">◀<small>왼쪽</small></button><button id="boatPause">출발하기 ▶</button><button id="steerRight" aria-label="문보트 오른쪽으로 이동">▶<small>오른쪽</small></button></div>';
   controls.innerHTML='<small id="gateCount"></small><h2>같은 속력이라면?</h2><div class="boat-condition">20초 동안 <strong>12m</strong></div><p id="gateQuestion"></p><div class="proportion"><span>시간</span><b id="seconds"></b><span>거리</span><b>? m</b></div><p class="small">정답 표지 아래로 직접 이동해요. 화면을 드래그하면 주변을 둘러봐요. 항해 시간은 짧게 재생해요.</p><button id="boatHint">항해 힌트</button><button id="retryLeg">이 관문 다시 출발</button><div class="central-route-progress"><span data-stop="0">이스트보트하우스</span><span data-stop="185">스트롤링가든브릿지</span><span data-stop="265">송도한옥마을 옆</span><span data-stop="355">UN광장 앞</span><span data-stop="420">토끼섬</span></div>';
   board.querySelector('.central-mini-map').onclick=()=>{pauseGame();CentralRouteMap.open();};const host=board.querySelector('.boat-view'),T=root.THREE;let renderer;
   try{if(!T)throw Error('3D library missing');renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){board.innerHTML='<div class="boat-clear"><h2>3D 화면을 준비하지 못했어요</h2><p>다른 3D 탭을 닫은 뒤 다시 시도해 주세요.<br>지금까지의 진행은 저장되어 있어요.</p></div>';controls.innerHTML='<button id="retry3d">3D 다시 준비하기</button>';controls.querySelector('#retry3d').onclick=start;confirm.hidden=true;return;}
   renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','실제 수로 위치를 반영한 송도 센트럴파크 문보트 항해');
   const scene=new T.Scene();scene.fog=new T.Fog('#b8cdd0',350,1500);const camera=new T.PerspectiveCamera(64,1,.1,2200);scene.add(new T.HemisphereLight('#d2eafa','#657052',.95));const sun=new T.DirectionalLight('#ffdbac',1.2);sun.position.set(-80,100,-150);scene.add(sun);
   const materials=[],textures=[],geometries=[];const mat=(color,extra={})=>{const m=new T.MeshStandardMaterial({color,roughness:.6,...extra});materials.push(m);return m;};
   function box(parent,w,h,d,x,y,z,m){const geo=new T.BoxGeometry(w,h,d);geometries.push(geo);const b=new T.Mesh(geo,m);b.position.set(x,y,z);parent.add(b);return b;}
   function tube(parent,points,r,m){const geo=new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),Math.max(12,points.length*3),r,6,false);geometries.push(geo);const o=new T.Mesh(geo,m);parent.add(o);return o;}
   const skyCanvas=document.createElement('canvas');skyCanvas.width=32;skyCanvas.height=512;const skyCtx=skyCanvas.getContext('2d'),skyGrad=skyCtx.createLinearGradient(0,0,0,512);skyGrad.addColorStop(0,'#5f94bf');skyGrad.addColorStop(.48,'#a8cddd');skyGrad.addColorStop(.65,'#ecdec3');skyGrad.addColorStop(1,'#cfdbd2');skyCtx.fillStyle=skyGrad;skyCtx.fillRect(0,0,32,512);const skyTexture=new T.CanvasTexture(skyCanvas);textures.push(skyTexture);const skyGeo=new T.SphereGeometry(1800,32,20),skyMat=new T.MeshBasicMaterial({map:skyTexture,side:T.BackSide,depthWrite:false,fog:false});geometries.push(skyGeo);materials.push(skyMat);scene.add(new T.Mesh(skyGeo,skyMat));
   const landscape=CentralWorld.build(T,scene,{materials,textures,geometries}),waterMat=landscape.waterMat,rail=mat('#809497',{metalness:.55}),lamp=mat('#ffe4a2',{emissive:'#ffc96f',emissiveIntensity:1});
   const boat=new T.Group();boat.name='moonboat';scene.add(boat);const ivory=mat('#dfede6',{roughness:.3,metalness:.15}),navy=mat('#173e53',{roughness:.38}),teal=mat('#147dd0',{emissive:'#086ede',emissiveIntensity:.65,roughness:.2}),seat=mat('#a2b8bc'),gold=mat('#e6cd97',{metalness:.6,roughness:.24});
   const hullGeo=new T.SphereGeometry(1,32,16);geometries.push(hullGeo);const hull=new T.Mesh(hullGeo,ivory);hull.scale.set(1.85,.42,3.1);hull.position.y=.12;boat.add(hull);box(boat,2.9,.2,4.9,0,.39,0,navy);box(boat,2.7,.3,1.15,0,.74,.85,seat);box(boat,2.7,1,.23,0,1.16,1.45,seat);box(boat,.32,.24,.72,.9,1,-.4,ivory);tube(boat,[[.9,1.1,-.4],[.9,1.48,-.35]],.055,navy);const knobGeo=new T.SphereGeometry(.13,10,8);geometries.push(knobGeo);const knob=new T.Mesh(knobGeo,navy);knob.position.set(.9,1.48,-.35);boat.add(knob);
   const crescent=new T.Shape();crescent.moveTo(-2.6,.46);crescent.bezierCurveTo(-.2,-.3,3.45,.25,2.4,3.7);crescent.bezierCurveTo(2.0,1.2,.5,.25,-2.6,.46);const moonGeo=new T.ExtrudeGeometry(crescent,{depth:.16,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.08,bevelThickness:.08,curveSegments:32});geometries.push(moonGeo);for(const side of [-1,1]){const moon=new T.Mesh(moonGeo,teal);moon.rotation.y=-Math.PI/2;moon.position.set(side*1.56,0,0);boat.add(moon);tube(boat,[[side*1.35,.72,-2.2],[side*1.35,.72,-.8],[side*1.35,1.15,1.4]],.055,gold);}
   const led=mat('#d2f4ff',{emissive:'#9ee9ff',emissiveIntensity:1.4});for(const side of [-1,1]){const pts=[];for(let n=0;n<=18;n++){const t=n/18,u=1-t;const z=u*u*u*2.4+3*u*u*t*2+3*u*t*t*.5+t*t*t*(-2.6),y=u*u*u*3.7+3*u*u*t*1.2+3*u*t*t*.25+t*t*t*.46;pts.push([side*1.66,y+.06,z]);}tube(boat,pts,.035,led);}
   const glowCanvas=document.createElement('canvas');glowCanvas.width=128;glowCanvas.height=128;const gc=glowCanvas.getContext('2d'),gg=gc.createRadialGradient(64,64,2,64,64,64);gg.addColorStop(0,'rgba(18,153,255,.65)');gg.addColorStop(.4,'rgba(10,119,248,.2)');gg.addColorStop(1,'rgba(0,80,255,0)');gc.fillStyle=gg;gc.fillRect(0,0,128,128);const glowTex=new T.CanvasTexture(glowCanvas);textures.push(glowTex);const glowMat=new T.MeshBasicMaterial({map:glowTex,transparent:true,depthWrite:false,blending:T.AdditiveBlending});materials.push(glowMat);const glowGeo=new T.PlaneGeometry(10,13);geometries.push(glowGeo);const glow=new T.Mesh(glowGeo,glowMat);glow.rotation.x=-Math.PI/2;scene.add(glow);
   const passengers=new T.Group();boat.add(passengers);const skin=mat('#f2c4a1'),hair=mat('#352e29'),jacket=mat('#ed893f');for(const side of [-1,1]){box(passengers,.55,.9,.45,side*.65,1.3,.65,navy);box(passengers,.64,.62,.5,side*.65,1.52,.63,jacket);const headGeo=new T.SphereGeometry(.32,14,12);geometries.push(headGeo);const head=new T.Mesh(headGeo,skin);head.position.set(side*.65,2,.63);passengers.add(head);const cap=new T.Mesh(headGeo,hair);cap.scale.set(1.03,.65,1.04);cap.position.set(side*.65,2.16,.65);passengers.add(cap);}
   const wakeGeo=new T.PlaneGeometry(2.8,7);geometries.push(wakeGeo);const wakeMat=new T.MeshBasicMaterial({color:'#b6e0df',transparent:true,opacity:.14,depthWrite:false});materials.push(wakeMat);const wake=new T.Mesh(wakeGeo,wakeMat);wake.rotation.x=-Math.PI/2;scene.add(wake);
   const gateGroup=new T.Group();scene.add(gateGroup);let gateTextures=[],gateMaterials=[],gateGeometry=[];
   function clearGates(){gateGroup.clear();gateTextures.forEach(t=>t.dispose());gateMaterials.forEach(m=>m.dispose());gateGeometry.forEach(g=>g.dispose());gateTextures=[];gateMaterials=[];gateGeometry=[];}
   function gateBoard(label){const cn=document.createElement('canvas');cn.width=512;cn.height=256;const cg=cn.getContext('2d');cg.fillStyle='#153945';cg.fillRect(0,0,512,256);cg.strokeStyle='#f1d19b';cg.lineWidth=12;cg.strokeRect(9,9,494,238);cg.fillStyle='#fff6d9';cg.font='bold 92px sans-serif';cg.textAlign='center';cg.fillText(label,256,167);const t=new T.CanvasTexture(cn);gateTextures.push(t);const m=new T.MeshBasicMaterial({map:t,side:T.DoubleSide});gateMaterials.push(m);const geo=new T.PlaneGeometry(4.1,2.05);gateGeometry.push(geo);return new T.Mesh(geo,m);}
   let arrived=M.solved('central',c.state),running=false,pov=true,targetLane=Math.max(0,Math.min(2,Math.round(s.x/4.8)+1)),frame=0,last=performance.now(),totalTime=0,failures=0,messageUntil=0,look=0,drag=null,lastSave=0;
   const lanternGeo=new T.SphereGeometry(.4,10,8);geometries.push(lanternGeo);
   function updateLeg(){clearGates();const l=M.legs[s.leg];if(!l)return;const gate=landscape.at(s.leg*150+146);gateGroup.position.copy(gate.point);gateGroup.rotation.y=gate.yaw;l.options.forEach((answer,i)=>{const x=(i-1)*4.8;const sign=gateBoard(answer+'m');sign.position.set(x,5,0);gateGroup.add(sign);box(gateGroup,.12,5,.12,x-2.2,2.5,0,rail);box(gateGroup,.12,5,.12,x+2.2,2.5,0,rail);const lantern=new T.Mesh(lanternGeo,lamp);lantern.position.set(x,7,0);gateGroup.add(lantern);});
    controls.querySelector('#gateCount').textContent='빛의 관문 '+(s.leg+1)+' / 3';controls.querySelector('#gateQuestion').innerHTML='<strong>'+l.seconds+'초</strong> 동안에는 몇 m를 갈까요?';controls.querySelector('#seconds').textContent=l.seconds+'초';board.querySelector('.lane-guide').innerHTML=l.options.map((n,i)=>`<span data-lane="${i}"><small>${['왼쪽','가운데','오른쪽'][i]}</small><strong>${n}m</strong></span>`).join('')+'<span class="boat-task-strip">20초에 12m → <b>'+l.seconds+'초에는?</b></span>';c.feedback('20초에 12m. 같은 속력일 때 '+l.seconds+'초 동안 가는 거리를 생각해 정답 쪽으로 이동해요.');}
   const eye=new T.Vector3(0,2.05,.05),cameraPosition=new T.Vector3(),cameraTarget=new T.Vector3(),viewDirection=new T.Vector3(),up=new T.Vector3(0,1,0);
   function updateCamera(here,dt=1/60,snap=false){
    viewDirection.copy(here.tangent).applyAxisAngle(up,look);
    if(pov&&!arrived){
     // Follow the seated eye exactly: easing behind a moving boat puts the camera through its backrest.
     boat.updateMatrixWorld(true);cameraPosition.copy(eye);boat.localToWorld(cameraPosition);camera.position.copy(cameraPosition);
     cameraTarget.copy(cameraPosition).addScaledVector(viewDirection,28);cameraTarget.y=cameraPosition.y+.15;
    }else{
     cameraPosition.copy(here.point).addScaledVector(here.tangent,pov?-1.15:-11).addScaledVector(here.right,pov?0:6);cameraPosition.y=arrived?4:6.5;
     if(snap)camera.position.copy(cameraPosition);else camera.position.lerp(cameraPosition,Math.min(1,dt*7));
     cameraTarget.copy(here.point).addScaledVector(viewDirection,pov?28:18);cameraTarget.y=pov?2:1.5;
    }
    if(arrived){const r=CentralGeography.places.rabbit;cameraTarget.set(r[0],10,r[1]);}
    camera.lookAt(cameraTarget);camera.updateMatrixWorld(true);
   }
   function applyView(){passengers.visible=!pov;board.dataset.view=pov?'first':'third';board.querySelector('#viewMode').textContent=pov?'3인칭으로 보기':'1인칭으로 보기';updateCamera(landscape.at(Math.min(450,s.leg*150+s.progress),s.x),1/60,true);}
   const pauseButton=board.querySelector('#boatPause');function pause(){running=false;pauseButton.textContent='계속 항해 ▶';}pauseGame=pause;
   pauseButton.onclick=()=>{if(arrived)return;running=!running;pauseButton.textContent=running?'잠깐 멈추기 Ⅱ':'계속 항해 ▶';};
   function steer(d){if(arrived)return;targetLane=Math.max(0,Math.min(2,targetLane+d));if(!running)c.feedback('방향을 정했어요. 출발하기·계속 항해를 누르면 움직여요.');}
   board.querySelector('#steerLeft').onclick=()=>steer(-1);board.querySelector('#steerRight').onclick=()=>steer(1);board.querySelector('#viewMode').onclick=()=>{pov=!pov;look=0;drag=null;applyView();};
   controls.querySelector('#boatHint').onclick=()=>{pause();const l=M.legs[s.leg];c.feedback(l.seconds===10?'10초는 20초의 절반! 거리도 12m의 절반이에요.':l.seconds===15?'5초에는 3m, 15초는 5초가 세 번이에요.': '30초는 20초의 1.5배! 12m에 그 절반을 더해 보세요.');};controls.querySelector('#retryLeg').onclick=()=>{s.progress=0;s.x=0;targetLane=1;pause();c.persist();c.feedback('이번 관문의 출발점으로 돌아왔어요. 앞서 통과한 관문은 유지돼요.');};
   function key(e){if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowLeft'){e.preventDefault();if(!e.repeat)steer(-1);}if(e.key==='ArrowRight'){e.preventDefault();if(!e.repeat)steer(1);}if(e.code==='Space'){e.preventDefault();pauseButton.click();}}window.addEventListener('keydown',key);
   const canvas=renderer.domElement;canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,look};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(drag)look=Math.max(-2.7,Math.min(2.7,drag.look-(e.clientX-drag.x)*.006));});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
   const ro=new ResizeObserver(()=>{const r=host.getBoundingClientRect();if(r.width&&r.height){renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}});ro.observe(host);
   function showMessage(text,good){const e=board.querySelector('.boat-message');e.textContent=text;e.className='boat-message '+(good?'good':'bad');e.hidden=false;messageUntil=totalTime+2;}
   function showArrival(){pause();clearGates();board.querySelector('.lane-guide').hidden=true;board.querySelector('.boat-inputs').hidden=true;controls.innerHTML='<small>항해 완료</small><h2>토끼섬의 수학의 빛</h2><p>섬 위에서 빛이 반짝이고 있어요.<br>이곳에서 세 번째 빛을 찾았어요!</p><p>토끼섬은 UN광장 가까이 수로 안에 있는 작은 섬이에요. 배에서 조용히 바라봐요.</p>';confirm.hidden=false;confirm.textContent='토끼섬 이야기 듣기 →';confirm.onclick=c.next;c.feedback('✦ 토끼섬의 수학의 빛을 찾았어요!','good');}
   function loop(now){frame=requestAnimationFrame(loop);const dt=Math.min(.04,(now-last)/1000);last=now;const held=document.hidden||!!document.querySelector('dialog[open]');if(held)return;totalTime+=dt;waterMat.uniforms.time.value=totalTime;
    s.x+=(targetLane*4.8-4.8-s.x)*Math.min(1,dt*4);if(running){s.progress+=dt*8;if(s.progress>=149){const lane=Math.max(0,Math.min(2,Math.round(s.x/4.8)+1)),leg=M.legs[s.leg];if(Math.abs(s.x-(lane-1)*4.8)<2.0&&leg.options[lane]===leg.answer){s.gates.push(leg.answer);s.leg++;s.progress=0;c.tone();if(s.leg>=3){s.proof={version:2,scale:450,gates:[...s.gates]};c.persist();pause();arrived=true;showArrival();}else{showMessage('✦ 정답! 빛을 품고 다음 관문으로',true);updateLeg();c.persist();}}else{failures++;s.progress=103;c.persist();c.tone(false);showMessage('다시 생각해 봐요 · 이 관문만 다시 도전',false);if(failures>=2)c.feedback('같은 속력에서는 시간과 거리가 같은 비율로 변해요. 항해 힌트를 눌러 천천히 생각해도 좋아요.','bad');}}
     if(now-lastSave>1200){c.persist();lastSave=now;}}
    const distance=Math.min(450,s.leg*150+s.progress),here=landscape.at(distance,s.x);boat.position.copy(here.point);boat.position.y=Math.sin(totalTime*1.6)*.035;boat.rotation.z=-(targetLane*4.8-4.8-s.x)*.013+Math.sin(totalTime*1.1)*.008;boat.rotation.y=here.yaw-(targetLane*4.8-4.8-s.x)*.023;glow.position.copy(here.point);glow.position.y=.02;glow.rotation.z=-here.yaw;wake.position.copy(here.point).addScaledVector(here.tangent,-6);wake.position.y=.025;wake.rotation.z=-here.yaw;wake.visible=running;
    updateCamera(here,dt);
    board.querySelector('#boatTravel').textContent=Math.floor(distance)+' / 약 450m';CentralRouteMap.update(board.querySelector('.central-mini-map'),here.point);board.querySelectorAll('[data-lane]').forEach(e=>e.classList.toggle('selected',Number(e.dataset.lane)===targetLane));
    const stops=[['이스트보트하우스','오른쪽 뒤 선착장을 떠나 굽은 물길을 따라가요.',0],['스트롤링가든브릿지','낮은 은백색 아치 아래를 통과해요.',165],['송도한옥마을','왼쪽 물가의 기와지붕과 나무 기둥을 찾아보세요.',245],['UN광장','왼쪽의 넓은 돌바닥 광장이 UN광장이에요.',335],['토끼섬 · 수학의 빛','작은 섬 위의 황금빛이 우리를 기다리고 있어요.',403]];const stop=stops.filter(q=>distance>=q[2]).at(-1);board.querySelector('#boatLocation').textContent=stop[0];const lm=board.querySelector('.boat-landmark');lm.hidden=!arrived&&!(distance-stop[2]<32);lm.querySelector('strong').textContent=stop[0];lm.querySelector('p').textContent=stop[1];controls.querySelectorAll('[data-stop]').forEach((el,i)=>{el.classList.toggle('passed',distance>stops[i][2]+30);el.classList.toggle('current',stop===stops[i]);});
    if(totalTime>messageUntil)board.querySelector('.boat-message').hidden=true;landscape.animate(totalTime,camera,distance);landscape.reflect(renderer,camera);renderer.render(scene,camera);
   }
   destroyGame=()=>{cancelAnimationFrame(frame);ro.disconnect();window.removeEventListener('keydown',key);clearGates();landscape.destroy();geometries.forEach(g=>g.dispose());scene.traverse(o=>{o.geometry?.dispose();});materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();};updateLeg();const initial=landscape.at(Math.min(450,s.leg*150+s.progress),s.x);boat.position.copy(initial.point);boat.rotation.y=initial.yaw;applyView();frame=requestAnimationFrame(loop);c.feedback('큰 좌우 버튼으로 정답 쪽을 고르고 출발해요. 화면을 드래그하면 주변 풍경을 둘러볼 수 있어요.');if(arrived)showArrival();if(innerWidth<=900)requestAnimationFrame(()=>{if(!dead)board.scrollIntoView({block:'start',behavior:'instant'});});
  }
  if(s.scale===450||M.solved('central',c.state))start();else scale();return {pause(){pauseGame();},destroy(){dead=true;destroyGame();confirm.onclick=null;}};
 }
 root.NamdongBoat={mount};
})(window);
