(()=>{'use strict';const $=id=>document.getElementById(id),id=document.body.dataset.course,M=NamdongMath,P=NamdongProgress,D=NamdongData,C=D.courses[id],A='asset/namdong-tour/';
 let state=M.fresh(),saved=null,run=P.status().run,play=null,timer=0,sound=false,audio=null,zoom=1;
 const current=()=>C.steps[state.step];
 function checkRun(){if(P.status().run===run&&P.status().items.find(c=>c.id===id)?.unlocked)return true;stop();$('main').inert=true;$('lockedText').textContent=P.status().run!==run?'지역 여행이 초기화되었어요. 월드맵에서 다시 출발해 주세요.':'챕터 '+(C.number-1)+'을 완료하면 이 여행이 열려요.';if(!$('locked').open)$('locked').showModal();return false;}
 function persist(finish=false){if(!checkRun())return false;const ok=P.save(id,state,run,finish);$('saveNotice').hidden=ok;return ok;}
 function stop(){clearTimeout(timer);play?.destroy();play=null;}
 function img(el,file,alt){if(['central-arrival.webp','central.webp','market-arrival.webp','market.webp','park-arrival.webp','park-landmark.webp','park.webp','meerkat.webp'].includes(file))file=file.replace('.webp','.webp');const src=A+file;if(el.getAttribute('src')!==src)el.src=src;el.alt=alt;}
 function tone(good=true){if(!sound)return;try{audio||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.setValueAtTime(good?660:230,audio.currentTime);o.frequency.exponentialRampToValueAtTime(good?990:180,audio.currentTime+.15);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.28);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.3);}catch{}}
 function feedback(text,kind=''){$('feedback').textContent=text;$('game').querySelector('.game-footer').className='game-footer '+kind;}
 function normalize(raw){const s=M.restore(raw);if(id==='park'&&!raw.zoo&&!M.solved('park',raw)){s.step=Math.min(s.step,4);s.line=0;s.departed=false;}if(id==='market'&&s.marketStoryVersion!==2){if(M.solved('market',s)){s.step=s.departed?C.steps.length-1:6;s.line=0;}else if(s.step>5){s.step=5;s.line=0;}s.marketStoryVersion=2;}s.step=Math.min(s.step,C.steps.length-1);for(let i=0;i<s.step;i++)if(C.steps[i].type==='game'&&!M.solved(id,s)){s.step=i;s.line=0;s.departed=false;break;}return s;}
 function go(n,line=0){if(!checkRun())return;stop();state.step=Math.min(n,C.steps.length-1);state.line=line;render();persist();}
 function next(){go(state.step+1);}
 function render(){stop();const s=current();document.querySelectorAll('main>.screen').forEach(e=>e.hidden=e.id!==s.type);$('main').dataset.screen=s.type;
  if(s.type==='arrival'||s.type==='departure'){img($(s.type).querySelector('.backdrop'),id+'-arrival.webp',C.title+' 여행 도착 장면 · 창작 일러스트');const b=$(s.type).querySelector('.road img');b.style.animation='none';void b.offsetWidth;b.style.animation='';if(s.type==='arrival'){$('arrival').querySelector('h1').textContent='이번 정류장은 '+C.title+'입니다.';$('arrival').querySelector('p').textContent='챕터 '+C.number+' · '+C.subtitle;$('resume').hidden=!saved;$('bus').classList.add('arriving');$('leaveBus').disabled=true;timer=setTimeout(()=>$('leaveBus').disabled=false,1600);}else{$('departure').querySelector('h1').textContent=s.title||'빛을 품고 다시 버스로';$('departure').querySelector('.arrival-copy small').textContent=s.eyebrow||'LIGHT FOUND';$('departureText').textContent=s.text||(C.nextId?'다음 정류장은 '+D.courses[C.nextId].title+'입니다.':'남동·연수 여행을 마치고 다시 매스투어 버스에 올라요.');timer=setTimeout(finish,4200);}}
  if(s.type==='story')renderStory();if(s.type==='photos')renderPhoto();
  if(s.type==='map'){$('mapTitle').textContent=s.title;$('mapText').textContent=s.text;const target=M.solved(id,state)?(C.nextId||'central'):id;document.querySelectorAll('.map-pin').forEach(e=>{const c=P.status().items.find(x=>x.id===e.dataset.place);e.classList.toggle('lit',c.completed||e.dataset.place===id&&M.solved(id,state));e.classList.toggle('target',e.dataset.place===target);});}
  if(s.type==='lesson'){const l=D.lessons[id];$('lessonTitle').textContent=l.title;$('lessonLead').textContent=l.lead;$('lessonMath').innerHTML=l.math;$('lessonText').textContent=l.text;$('lessonHow').textContent=l.how;$('lessonNote').textContent=l.note;img($('lesson').querySelector('img'),l.art.includes('.')?l.art:l.art+'.webp',l.lead);}
  if(s.type==='game'){$('game').dataset.kind=id;$('board').replaceChildren();$('controls').replaceChildren();$('confirm').hidden=false;$('confirm').disabled=false;$('gameEyebrow').textContent='MISSION · '+C.subtitle;$('gameTitle').textContent={park:'미어캣 행동 관찰 기록',market:'꽃게를 담을 상자를 만들어요',central:'문보트를 타고, 마지막 빛을 향해'}[id];const ctx={state,persist,feedback,tone,next,checkRun,board:$('board'),controls:$('controls'),confirm:$('confirm')};play=(id==='central'?NamdongBoat:NamdongGames).mount(id,ctx);}
  if(s.type==='ending'){if(!M.solved('central',state)){go(C.steps.findIndex(s=>s.type==='game'));return;}$('ending').classList.remove('lit');void $('ending').offsetWidth;$('ending').classList.add('lit');tone();timer=setTimeout(next,16000);}
  if(s.type==='recap'){img($('recap').querySelector('img'),(C.recapArt||C.art)+'.webp',C.recapTitle||C.title+'의 빛');$('recap').querySelector('article>small').textContent=C.recapLabel||'CHAPTER COMPLETE';$('recapTitle').textContent=C.recapTitle||(C.nextId?C.title+'의 빛을 찾았어요':'남동·연수의 빛이 모두 모였어요');$('recapText').textContent=C.recap;$('stamps').innerHTML=P.status().items.filter(c=>c.completed).map(c=>'<span>✦ '+c.title+'</span>').join('');$('nextChapter').textContent=C.nextLabel||(C.nextId?'챕터 '+D.courses[C.nextId].number+' · '+D.courses[C.nextId].title+' →':'지역 월드맵으로 →');$('nextChapter').href=C.nextId?P.url(C.nextId):P.mapURL;}
 }
 function renderStory(){const s=current();state.line=Math.min(state.line,s.lines.length-1);const [who,text]=s.lines[state.line];img($('story').querySelector('.backdrop'),s.art.includes('.')?s.art:s.art+'.webp',s.title+' 일러스트');$('story').classList.toggle('dim',!!s.dim);$('story').classList.toggle('zoo-story',!!s.keeper);const animal=$('story').querySelector('.zoo-story-animal');if(animal)animal.hidden=!s.keeper;const keeper=$('story').querySelector('.keeper');if(keeper){keeper.hidden=!s.keeper;keeper.classList.toggle('speaking',who==='사육사');}$('story').querySelector('.scene-tag').textContent=s.title;$('story').querySelector('.real-open').hidden=!s.photo;$('story').querySelector('.real-open').textContent=s.photoLabel||'실제 배경 보기';$('speaker').textContent=who;$('lineText').textContent=text;$('lineCount').textContent=(state.line+1)+' / '+s.lines.length;$('storyPrev').disabled=state.line===0;$('storyNext').textContent=state.line===s.lines.length-1?(s.nextLabel||'계속 여행하기 →'):'다음 →';$('story').querySelector('.minwoo').classList.toggle('speaking',who==='민우');$('story').querySelector('.seoyeon').classList.toggle('speaking',who==='서연');renderMerchant(s,who);}
 function renderMerchant(s,who){
  const present=id==='market'&&s.lines.some(([speaker])=>speaker==='상인');
  let merchant=$('storyMerchant');
  if(present&&!merchant){merchant=document.createElement('img');merchant.id='storyMerchant';merchant.className='person merchant';merchant.src=A+'merchant.webp';merchant.alt='소래포구 어시장 상인';$('story').insertBefore(merchant,$('story').querySelector('.dialogue'));}
  if(merchant){merchant.hidden=!present;merchant.classList.toggle('speaking',who==='상인');}
  $('story').classList.toggle('has-merchant',present);
 }
 function renderPhoto(){const s=current();state.line=Math.min(state.line,s.ids.length-1);const p=D.photos[s.ids[state.line]];$('photos').querySelector('.section-title h1').textContent=s.title||'눈으로 먼저 떠나는 여행';$('photos').classList.toggle('zoo-photo-page',!!p.extras);const extras=$('zooPhotoExtras');if(extras){extras.replaceChildren();extras.hidden=!p.extras;if(p.extras){const cards=document.createElement('div');cards.className='zoo-animal-previews';p.extras.forEach(a=>{const figure=document.createElement('figure'),picture=document.createElement('img'),caption=document.createElement('figcaption');picture.src=A+a.file;picture.alt=a.alt;caption.textContent=a.title;figure.append(picture,caption);cards.append(figure);});const source=document.createElement('a');source.href=p.extrasSource;source.target='_blank';source.rel='noopener';source.textContent='동물 사진 · 인천광역시 공식 동물소개 ↗';extras.append(cards,source);}}img($('photoImage'),p.file,p.title);$('photoCount').textContent=(state.line+1)+' / '+s.ids.length;$('photoTitle').textContent=p.title;$('photoText').textContent=p.text;$('photoCredit').textContent='실제 사진 · '+p.credit;$('photoSource').href=p.source;$('photoSource').textContent=p.extras?'동물원 입구 사진 출처 ↗':'관광 안내 출처 ↗';$('photoPrev').disabled=state.line===0;$('photoNext').textContent=state.line===s.ids.length-1?'여행 이어가기 →':'다음 사진 →';}
 function advance(type,back=false){const s=current();if(s.type!==type)return;const count=type==='story'?s.lines.length:s.ids.length;if(back){if(state.line>0)state.line--;}else if(state.line<count-1)state.line++;else return next();(type==='story'?renderStory:renderPhoto)();persist();}
 function finish(){if(current().type!=='departure'||!M.solved(id,state)||!checkRun())return;state.departed=true;persist(true);next();}
 $('storyNext').onclick=()=>advance('story');$('storyPrev').onclick=()=>advance('story',true);$('photoNext').onclick=()=>advance('photos');$('photoPrev').onclick=()=>advance('photos',true);$('leaveBus').onclick=next;$('begin').onclick=next;$('mapNext').onclick=next;$('endingNext').onclick=next;$('finishDeparture').onclick=finish;
 $('resume').onclick=()=>{if(!saved||!checkRun())return;state=normalize(saved);saved=null;render();persist();};
 $('story').querySelector('.real-open').onclick=()=>{const p=D.photos[current().photo];if(!p)return;$('realTitle').textContent=p.title;img($('realImage'),p.file,p.title);$('realCaption').textContent=p.credit;$('realSource').href=p.source;$('photoDialog').showModal();};
 function mapDialog(){play?.pause();zoom=1;$('largeMap').style.width='100%';$('zoomValue').textContent='100%';$('mapDialog').showModal();}
 $('enlargeMap').onclick=mapDialog;$('noteMap').onclick=()=>{$('note').close();mapDialog();};
 function zoomMap(delta){zoom=Math.min(3,Math.max(1,zoom+delta));$('largeMap').style.width=zoom*100+'%';$('zoomValue').textContent=Math.round(zoom*100)+'%';}$('zoomIn').onclick=()=>zoomMap(.5);$('zoomOut').onclick=()=>zoomMap(-.5);
 $('help').onclick=()=>{play?.pause();const l=play?.help?play.help():D.lessons[id];$('helpTitle').textContent=l.title;$('helpMath').innerHTML=l.math;$('helpText').textContent=l.text;$('helpHow').textContent=l.how;$('helpNote').textContent=l.note;$('helpDialog').showModal();};
 $('journal').onclick=()=>{play?.pause();$('noteBody').innerHTML='<p>지도에 남은 두 조각의 빛을 찾아 남동·연수를 여행해요.</p><div class="journal-chapters">'+P.status().items.map(c=>'<p>'+(c.completed||c.id===id&&M.solved(id,state)?'✦ ':'○ ')+c.title+'</p>').join('')+'</div><p class="small">학생 공동 원안의 탐험지도, 동물 행동 관찰과 평균·띠그래프, 꽃게 상자의 부피·겉넓이와 무게 나누기, 축척과 문보트 항해를 살려 구성했어요.</p>';$('sourceList').innerHTML=Object.entries(D.sources).map(([k,url])=>'<p><a target="_blank" rel="noopener" href="'+url+'">'+({park:'인천대공원',garden:'인천수목원',zoo:'어린이동물원 소개',meerkat:'미어캣의 경계 행동',market:'소래포구',shrimpTower:'새우타워',soraePlaza:'해오름광장과 황금 꽃게',central:'센트럴파크',boats:'송도 수상레저',moon:'문보트 소개'}[k])+' 관광 자료 ↗</a></p>').join('');$('note').showModal();};
 $('restartOpen').onclick=()=>{$('note').close();$('restartDialog').showModal();};$('restart').onclick=()=>{$('restartDialog').close();state=M.fresh();saved=null;go(0);};
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('sound').setAttribute('aria-pressed',sound);if(sound)tone();};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('locked').addEventListener('cancel',e=>e.preventDefault());
 window.addEventListener('mathtour:namdong-progress',checkRun);document.addEventListener('visibilitychange',()=>{if(document.hidden)play?.pause();else checkRun();});window.addEventListener('pagehide',()=>{play?.pause();if(state.step>0)persist();});
 if(!checkRun())return;const old=P.load(id);if(old?.step>0)saved=normalize(old);render();
})();
