(function(root){
 'use strict';
 const M=root.IslandMath,$=id=>document.getElementById(id),n=v=>Number(v.toFixed(1)).toLocaleString('ko-KR'),litres=v=>Math.round(v).toLocaleString('ko-KR')+' L';
 root.IslandBath={mount({state,persist,feedback,tone,next,checkRun,poolIllustration}){
  const board=$('board'),controls=$('controls'),confirm=$('confirm'),game=$('game'),layout=board.parentElement,header=game.querySelector('.section-title'),footer=game.querySelector('.game-footer'),help=$('help');
  const toolbar=document.createElement('div');toolbar.className='bath-top-actions';header.append(toolbar);toolbar.append(help,confirm);layout.insertBefore(controls,board);game.classList.add('bath-mode');layout.dataset.play='bath';
  let round=0,spa=null,running=false,slow=false,disposed=false,frame=0,last=0,lastDraw=0;
  if(state.spa.rules!==2){state.spa={rules:2,rounds:[],events:[],clock:0};persist();}
  function bind(id,fn){$(id).onclick=()=>{if(!disposed&&checkRun())fn();};}
  function primary(label,fn){confirm.textContent=label;confirm.disabled=false;confirm.onclick=()=>{if(!disposed&&checkRun())fn();};}
  function restore(){round=state.spa.rounds.length;if(round>=3)return;spa=M.bathReplay(round,state.spa.events);if(!spa||spa.status!=='playing'){state.spa.events=[];state.spa.clock=0;spa=M.bathCreate(round);}if(state.spa.clock>spa.time)M.bathAdvance(spa,state.spa.clock-spa.time);running=false;last=0;}
  function reset(){running=false;state.spa.events=[];state.spa.clock=0;spa=M.bathCreate(round);persist();render();feedback('이번 운영만 다시 준비했어요. 필요한 물과 배관의 최대 공급량을 비교해 보세요.');}
  function render(){board.className='board spa-scene';board.style.backgroundImage="url('asset/island-tour/spa-deck-v2.webp')";
   if(M.solved(state,'spa')){board.innerHTML=`<div class="spa-final"><span>✦</span><h2>노을 온천, 준비 완료!</h2><p>물의 양과 공급 속도를 생각해 모두 준비했어요.</p><div class="happy-guests">${[2,3,4].map((a,i)=>poolIllustration(a,3,true,false,i)).join('')}</div></div>`;controls.innerHTML='<div class="play-win"><span class="win-symbol">✦</span><h2>함께 즐기는 노을</h2><p>천천히 차는 큰 탕을 미리 준비하고, 남은 물을 다른 탕으로 나눠 보냈어요.</p></div>';primary('다음 이야기 →',next);feedback('필요한 물 ÷ 공급 속도! 걸리는 시간을 비교해 온천의 빛을 찾았어요.','good');return;}
   const c=M.bathRounds[round];
   controls.innerHTML=`<div class="bath-source"><small>온천수 분배소</small><h2>최대 ${c.flow} <span>L/초</span></h2><div id="bathTotal"></div></div><div class="bath-reserve"><span id="bathReserve"></span><meter id="bathReserveMeter" max="${c.budget}" min="0"></meter></div><div class="bath-rates-title" id="bathRatesTitle"></div><div class="bath-rates">${c.areas.map((area,i)=>`<article class="bath-rate" data-pool="${i}"><header><span>${M.poolNames[i]}</span><b id="bathRate${i}"></b></header><small id="bathVolume${i}"></small></article>`).join('')}</div><div class="bath-principle"><b>걸리는 시간</b><span> = 필요한 물 ÷ 공급 속도</span></div><div class="bath-tools"><button id="bathSlow" aria-pressed="${slow}">${slow?'천천히 켜짐':'천천히'}</button><button id="bathRetry">다시 준비</button></div><p class="bath-rule">배관이 받을 수 있는 최대량을 넘는 물은 다른 열린 배관으로 나눠요.</p>`;
   board.innerHTML=`<div class="spa-topline"><span>운영 ${round+1} / 3</span><b>${c.title}</b><span id="bathTime"></span></div><div class="pool-row" data-count="${c.areas.length}">${c.areas.map((area,i)=>`<article class="pool-card" data-pool="${i}"><header><strong>${M.poolNames[i]}</strong><small>밑넓이 ${area} m²</small><span id="bathDeadline${i}"></span></header><div class="bath-pipe-limit"><strong>필요한 물 ${litres(area*300)}</strong><span>배관 최대 ${c.caps[i]} L/초</span></div><div id="bathArt${i}" class="pool-art"></div><div class="pool-measure"><div class="pool-gauge"><span class="target-zone"></span><span id="bathGauge${i}" class="pool-gauge-fill"></span><b class="target-mark"></b></div><span id="bathHeight${i}"></span></div><button id="bathValve${i}" class="valve"></button><button id="bathDrain${i}" class="drain">물높이 5 cm 낮추기</button></article>`).join('')}</div><div class="spa-board-note">목표 높이 30 cm · 초록 구간 28~33 cm에서 잠그기</div>`;
   c.areas.forEach((_,i)=>{bind('bathValve'+i,()=>operate('toggle',i));bind('bathDrain'+i,()=>operate('drain',i));});
   bind('bathSlow',()=>{slow=!slow;$('bathSlow').textContent=slow?'천천히 켜짐':'천천히';$('bathSlow').setAttribute('aria-pressed',slow);});bind('bathRetry',reset);update();
  }
  function update(){if(disposed||!spa||M.solved(state,'spa')&&!$('bathTime'))return;const c=M.bathRounds[round],rates=M.bathRates(spa),total=rates.reduce((a,b)=>a+b,0);
   $('bathTime').textContent=(running?'운영 중 ':'여행 시계 ')+n(spa.time)+'초';$('bathTotal').textContent='열린 배관 합계 '+n(total)+' L/초';$('bathReserve').textContent='남은 물 '+litres(Math.max(0,c.budget-spa.used));$('bathReserveMeter').value=Math.max(0,c.budget-spa.used);$('bathRatesTitle').textContent=running?'현재 각 탕에 공급되는 물':'운영할 때 각 탕에 공급될 물';
   c.areas.forEach((area,i)=>{const h=M.bathHeight(spa,i),good=h>=M.BATH_LOW&&h<=M.BATH_HIGH,ready=spa.done[i];$('bathRate'+i).textContent=n(rates[i])+' L/초';$('bathVolume'+i).textContent='현재 '+litres(spa.volumes[i])+' / 목표 '+litres(area*300);$('bathArt'+i).innerHTML=poolIllustration(area,h/10,ready,spa.open[i]&&running,i).replace('0 0 300 280','0 105 300 175');$('bathGauge'+i).style.width=(h/M.BATH_MAX*100)+'%';$('bathGauge'+i).classList.toggle('good',good);$('bathHeight'+i).textContent=(ready?'준비 완료 · ':'물높이 ')+n(h)+' cm';$('bathDeadline'+i).textContent=ready?'손님 맞을 준비 완료':'손님 도착 '+n(Math.max(0,c.deadlines[i]-spa.time))+'초 뒤';$('bathDeadline'+i).classList.toggle('urgent',!ready&&c.deadlines[i]-spa.time<4);const v=$('bathValve'+i);v.textContent=ready?'✓ 준비 완료':spa.open[i]?(good?'지금 잠그기 ✓':'물 잠그기'):'물 켜기';v.setAttribute('aria-pressed',spa.open[i]);v.classList.toggle('in-zone',good&&spa.open[i]);v.disabled=ready||spa.status!=='playing';$('bathDrain'+i).disabled=ready||spa.open[i]||spa.volumes[i]<=0||spa.status!=='playing';});
   $('bathRetry').disabled=spa.status==='won';$('bathSlow').disabled=spa.status!=='playing';
   if(spa.status==='failed'){running=false;primary('이번 운영 다시 하기',reset);feedback(spa.reason,'bad');}
   else if(spa.status==='won'){running=false;primary(round<2?'다음 운영 도전 →':'온천의 빛 받기 →',()=>{round=state.spa.rounds.length;state.spa.events=[];state.spa.clock=0;if(round<3)spa=M.bathCreate(round);render();if(round<3)feedback(M.bathRounds[round].lead);});feedback('모든 탕 준비 완료! 사용한 물 '+litres(spa.used)+' · '+n(spa.time)+'초','good');}
   else primary(running?'Ⅱ 운영 멈추기':spa.time?'▶ 운영 계속하기':'▶ 운영 시작하기',()=>{running=!running;last=0;state.spa.clock=spa.time;persist();update();feedback(running?'왼쪽 공급량을 보며 초록 구간에서 잠그세요. 배관이 느린 탕도 미리 준비해요.':'시간이 멈췄어요. 밸브를 바꿔 공급량을 살펴본 뒤 계속할 수 있어요.');});
  }
  function operate(op,i){if(!spa||spa.status!=='playing')return;const event={t:spa.time,op,i};if(!M.bathOperate(spa,op,i))return;state.spa.events.push(event);state.spa.clock=spa.time;if(spa.status==='won'){running=false;state.spa.rounds[round]=state.spa.events.map(e=>({...e}));state.spa.events=[];state.spa.clock=0;tone();}persist();update();}
  function tick(ts){if(disposed)return;if(running&&spa?.status==='playing'){if(last){M.bathAdvance(spa,Math.min((ts-last)/1000,.1)*(slow?.5:1));if(spa.status==='failed'){running=false;tone(false);}if(ts-lastDraw>80){update();lastDraw=ts;}}last=ts;}else last=0;frame=requestAnimationFrame(tick);}
  function pause(){if(spa?.status==='playing'){running=false;last=0;state.spa.clock=spa.time;persist();update();}}
  window.addEventListener('blur',pause);restore();render();if(!M.solved(state,'spa'))feedback(M.bathRounds[round].lead+' 밸브를 고르고 오른쪽 위에서 시작하세요.');frame=requestAnimationFrame(tick);
  return {pause,destroy(){disposed=true;running=false;cancelAnimationFrame(frame);window.removeEventListener('blur',pause);confirm.onclick=null;footer.append(confirm);header.append(help);toolbar.remove();layout.append(controls);layout.removeAttribute('data-play');game.classList.remove('bath-mode');board.style.backgroundImage='';}};
 }};
})(window);
