(function(root){
 'use strict';
 const M=root.IslandMath,A='asset/island-tour/';
 const fmt=v=>Number(v.toFixed(2)).toString().replace('-','−');
 const text=(x,y,value,size=15,extra='')=>`<text x="${x}" y="${y}" text-anchor="middle" font-size="${size}" fill="#fff1cd" ${extra}>${value}</text>`;
 const math=v=>String(v).replace('-','−');
 root.IslandDrill={mount({state,persist,feedback,tone,next,checkRun}){
  const board=document.getElementById('board'),controls=document.getElementById('controls'),button=document.getElementById('confirm'),layout=board.parentElement;
  const gx=x=>130+x*34,gy=y=>70-y*34;
  let dir=1,tilt=1,progress=0,active=false,failed=false,hint=false,frame=0,last=0,disposed=false;
  if(!M.solved(state,'supply')&&M.drillProgress(state.supply)<0)state.supply={mode:'drill',legs:[]};
  const index=()=>Math.max(0,M.drillProgress(state.supply)),a=()=>[.5,1,2][tilt]*dir;
  const plan=()=>M.drillPlan(index(),a(),dir);
  const path=points=>points.map((p,i)=>`${i?'L':'M'}${gx(p.x)} ${gy(p.y)}`).join(' ');
  const bind=(id,fn)=>document.getElementById(id).onclick=()=>{if(!disposed&&checkRun())fn();};
  function equation(slope,p){const b=p.y-slope*p.x;return `<i>y</i> = ${slope===1?'':slope===-1?'−':M.format(slope)}<i>x</i>${b===0?'':b>0?' + '+M.format(b):' − '+M.format(-b)}`;}
  function actor(){const angle=Math.atan2(-a()*dir,dir)*180/Math.PI;return `<g class="drill-character"><ellipse cy="29" rx="38" ry="10" fill="#13262c" opacity=".35"/><image href="asset/민우.svg" x="-48" y="-99" width="96" height="118"/><path d="M-21 -67Q-20 -94 0 -94Q20 -94 22 -67Z" fill="#eac06b" stroke="#6a542e" stroke-width="2"/><path d="M-25 -67H26" stroke="#fff0b1" stroke-width="5" stroke-linecap="round"/><rect x="-31" y="10" width="64" height="21" rx="10" fill="#273c40" stroke="#19262a" stroke-width="2"/>${[-21,-7,7,21].map(x=>`<circle cx="${x}" cy="20" r="6" fill="#758481" stroke="#d6d2b5" stroke-width="1.5"/>`).join('')}<path d="M-29 -14Q0 -24 30 -14L35 9Q0 22 -35 9Z" fill="#d4a453" stroke="#705935" stroke-width="2"/><path d="M-19 -10H17V4H-19Z" fill="#446b70" stroke="#f3db97" stroke-width="2"/><circle cx="-24" cy="5" r="3" fill="#fff3ae"/><g transform="rotate(${angle})"><path d="M0 0H34" stroke="#d3dad0" stroke-width="12"/><path d="M0 0H32" stroke="#5d7575" stroke-width="5"/><g class="drill-teeth"><path d="M29 -12L55 0L29 12Z" fill="#e3e6d6" stroke="#537072" stroke-width="2"/><path d="M32 -10L38 7M39 -7L44 5M46 -4L49 2" stroke="#71858a" stroke-width="3"/></g><g class="drill-dust" fill="#ffdda0">${[[-9,62,0],[-4,62,11],[8,69,-7],[4,58,-17]].map(([r,x,y])=>`<path d="M${x} ${y}l4 -3 3 5-5 3Z" transform="rotate(${r} ${x} ${y})"/>`).join('')}</g></g></g>`;}
  function scene(){let grid='',rocks='';for(let k=1;k<=10;k++)grid+=`<path d="M${gx(k)} ${gy(0)}V${gy(-10)}M${gx(0)} ${gy(-k)}H${gx(10)}" stroke="#dccb9e" opacity=".13"/>`+text(gx(k),57,k,14)+text(110,gy(-k)+5,'−'+k,14);
   for(let k=0;k<42;k++){const x=138+(k*73)%322,y=85+(k*47)%310,s=8+k%7;rocks+=`<path d="M${x-s} ${y}l${s*.4} -${s*.8} ${s} -2 ${s*.7} ${s*.7}-${s*.4} ${s*.9}-${s} 3Z" fill="${k%2?'#53625d':'#7a7960'}" stroke="#263f3d" stroke-width="1" opacity=".5"/>`;}
   const won=M.solved(state,'supply'),stage=index(),points=[M.source,...M.drillStages.slice(0,won?3:stage)],p=won?null:plan();
   board.innerHTML=`<svg viewBox="0 0 600 480" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs><linearGradient id="drillEarth" x2="0" y2="1"><stop stop-color="#ae9165"/><stop offset=".4" stop-color="#45605a"/><stop offset="1" stop-color="#183e48"/></linearGradient><marker id="drillArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M1 1L9 5L1 9" fill="none" stroke="#fff0bd" stroke-width="1.4"/></marker><clipPath id="drillClip"><rect x="130" y="70" width="340" height="340"/></clipPath></defs><rect width="600" height="480" fill="url(#drillEarth)"/><image href="${A}spa-deck-v2.webp" width="600" height="38" preserveAspectRatio="xMidYMid slice"/><rect x="116" y="61" width="369" height="365" rx="9" fill="#183e3b" opacity=".65"/>${rocks}${grid}<g stroke="#fff0bd" stroke-width="1.6" fill="none"><path d="M94 70H500" marker-end="url(#drillArrow)"/><path d="M130 428V30" marker-end="url(#drillArrow)"/></g>${text(492,96,'x',21,'class="math-label"')}${text(113,42,'y',21,'class="math-label"')}${text(112,91,'O',18,'class="math-label"')}<g clip-path="url(#drillClip)">${p?`<path d="${path([p.from,p.to])}" stroke="#fae09d" stroke-width="2" stroke-dasharray="5 7" fill="none" opacity=".8"/>`:''}<path d="${path(points)}" stroke="#dec195" stroke-width="31" fill="none" stroke-linejoin="round" stroke-linecap="round"/><path d="${path(points)}" stroke="#172f35" stroke-width="25" fill="none" stroke-linejoin="round" stroke-linecap="round"/><path class="water-stream" d="${path(points)}" stroke="#8ce0d8" stroke-width="9" fill="none" stroke-linejoin="round"/><path id="drillTraceEdge" stroke="#dec195" stroke-width="30" fill="none" stroke-linecap="round"/><path id="drillTrace" stroke="#172f35" stroke-width="23" fill="none" stroke-linecap="round"/><path id="drillWater" class="water-stream" stroke="#8ce0d8" stroke-width="8" fill="none"/></g>${M.drillStages.map((v,i)=>`<g><circle cx="${gx(v.x)}" cy="${gy(v.y)}" r="20" fill="${i<stage||won?'#719a82':'#ead4a0'}" stroke="${i===stage&&!won?'#fff1b4':'#99805b'}" stroke-width="${i===stage&&!won?4:2}"/>${text(gx(v.x),gy(v.y)+6,v.name,19,'style="fill:#263f3e"')}${i<stage||won?text(gx(v.x)+18,gy(v.y)-17,'✓',17):''}</g>`).join('')}<circle cx="${gx(2)}" cy="${gy(-10)}" r="11" fill="#9ee6dd"/>${won?'':`<g id="drillActor">${actor()}</g>`}${text(300,462,'지표면 y = 0 · −10칸 = 지하 460m · 체험용 굴착 지도',13)}</svg><div class="drill-stage-tag">${won?'물길 연결 완료':`물길 ${stage+1} / 3 · ${M.drillStages[stage].name} 연결실로`}</div>`;
  }
  function render(){if(disposed)return;board.className='board drill-scene';board.style.backgroundImage='';layout.dataset.play='drill';scene();
   if(M.solved(state,'supply')){controls.innerHTML='<div class="play-win"><span class="win-symbol">✦</span><h2>민우가 물길을 뚫었어요!</h2><p>C → B → A 연결 완료!<br>기울기 2, 1/2, −1로 이어진 물길을 따라 온천수가 올라와요.</p><div class="student-credit">김주원 학생의 좌표·일차함수 배관 원안</div></div>';button.textContent='다음 이야기 →';button.disabled=false;button.onclick=()=>{if(checkRun())next();};feedback('좌표의 가로·세로 변화를 살펴 세 물길을 직접 이어 냈어요.','good');return;}
   const p=plan(),dx=p.target.x-p.from.x,dy=p.target.y-p.from.y,locked=progress>0;
   controls.innerHTML=`<div class="task-kicker">민우의 굴착기 · 김주원 학생 원안</div><h2>${p.target.name} 연결실로 물길 뚫기</h2><div class="drill-coordinate"><span>출발 (${p.from.x}, ${math(p.from.y)})</span><strong>목표 (${p.target.x}, ${math(p.target.y)})</strong></div><div class="drill-direction"><button id="drillLeft" aria-pressed="${dir===-1}" ${locked?'disabled':''}>↖ 왼쪽</button><button id="drillRight" aria-pressed="${dir===1}" ${locked?'disabled':''}>오른쪽 ↗</button></div><div class="drill-angle"><button id="drillLess" aria-label="드릴 더 완만하게" ${locked||tilt===0?'disabled':''}>−</button><div><small>기울기</small><output>${M.format(a())}</output></div><button id="drillMore" aria-label="드릴 더 가파르게" ${locked||tilt===2?'disabled':''}>＋</button></div><div class="drill-equation">${equation(a(),p.from)}</div><p class="drill-readout" id="drillReadout"></p><div class="drill-actions"><button id="drillReset">↶ 이번 구간 되돌리기</button><button id="drillHint" aria-pressed="${hint}">좌표 힌트</button></div><p class="drill-tip">${hint?`${dx>0?'오른쪽':'왼쪽'} ${Math.abs(dx)}칸, 위로 ${dy}칸.<br>기울기 = ${dy} ÷ (${math(dx)})`:'방향과 기울기를 정하고 굴착해요.<br>연결실에 닿으면 자동으로 멈춰요.'}</p>`;
   bind('drillLeft',()=>choose(-1,tilt));bind('drillRight',()=>choose(1,tilt));bind('drillLess',()=>choose(dir,Math.max(0,tilt-1)));bind('drillMore',()=>choose(dir,Math.min(2,tilt+1)));
   bind('drillReset',()=>{active=false;failed=false;progress=0;render();feedback('이번 구간의 시작점으로 돌아왔어요. 이미 연결한 물길은 남아 있어요.');});
   bind('drillHint',()=>{hint=!hint;render();});button.disabled=false;button.onclick=toggle;update();
  }
  function choose(d,t){if(progress>0)return;dir=d;tilt=t;failed=false;render();feedback('점선은 드릴이 나아갈 방향이에요. 목표 연결실을 향하는지 살펴봐요.');}
  function update(){if(disposed||M.solved(state,'supply'))return;const p=plan(),q={x:p.from.x+(p.to.x-p.from.x)*progress,y:p.from.y+(p.to.y-p.from.y)*progress};
   document.getElementById('drillActor').setAttribute('transform',`translate(${gx(q.x)} ${gy(q.y)})`);
   for(const id of ['drillTraceEdge','drillTrace','drillWater'])document.getElementById(id).setAttribute('d',progress?path([p.from,q]):'');
   document.getElementById('drillWater').setAttribute('stroke',failed?'#d89473':'#8ce0d8');board.classList.toggle('drill-active',active);
   document.getElementById('drillReadout').textContent=`민우 (${fmt(q.x)}, ${fmt(q.y)}) · 이번 구간 ${Math.round(progress*100)}%`;
   button.textContent=failed?'이번 구간 다시 준비하기':active?'■ 굴착 멈추기':progress?'▶ 이어서 굴착하기':'▶ 굴착 시작';
   ['drillLeft','drillRight','drillLess','drillMore'].forEach(id=>{const b=document.getElementById(id);b.disabled=progress>0||(id==='drillLess'&&tilt===0)||(id==='drillMore'&&tilt===2);});
  }
  function toggle(){if(disposed||!checkRun()||M.solved(state,'supply'))return;if(failed){failed=false;progress=0;active=false;render();feedback('도착 좌표를 목표와 비교하고 방향을 다시 정해요.');return;}active=!active;last=0;update();feedback(active?'민우가 암반을 뚫고 있어요. 버튼을 다시 누르면 멈춰요.':'굴착을 멈췄어요. 방향을 바꾸려면 이번 구간 되돌리기를 눌러요.');}
  function tick(ts){if(disposed)return;if(active){if(last){const p=plan();progress=Math.min(1,progress+Math.min((ts-last)/1000,.08)*1.3/Math.max(p.length,.3));update();if(progress>=1){active=false;if(p.correct){state.supply.legs.push({a:a(),dir});persist();tone();progress=0;failed=false;hint=false;render();if(!M.solved(state,'supply'))feedback(`${p.target.name} 연결 성공! 기울기 ${M.format(M.slope(p.from,p.target))}로 뚫었어요. 다음 연결실의 좌표를 살펴봐요.`,'good');}else{failed=true;tone(false);update();feedback(`민우가 (${fmt(p.to.x)}, ${fmt(p.to.y)})에 도착했어요. 목표 ${p.target.name}(${p.target.x}, ${math(p.target.y)})에 닿도록 이번 구간을 다시 준비해요.`,'bad');}}}last=ts;}else last=0;frame=requestAnimationFrame(tick);}
  function pause(){active=false;last=0;if(!disposed)update();}
  function key(e){if(document.querySelector('dialog[open]')||M.solved(state,'supply'))return;const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'];if(!keys.includes(e.key)||progress>0)return;e.preventDefault();if(e.key==='ArrowLeft')choose(-1,tilt);if(e.key==='ArrowRight')choose(1,tilt);if(e.key==='ArrowUp')choose(dir,Math.min(2,tilt+1));if(e.key==='ArrowDown')choose(dir,Math.max(0,tilt-1));}
  document.addEventListener('keydown',key);window.addEventListener('blur',pause);render();if(!M.solved(state,'supply'))feedback('민우와 함께 C → B → A 순서로 물길을 뚫어요. 현재 목표는 '+M.drillStages[index()].name+' 연결실이에요.');frame=requestAnimationFrame(tick);
  return {pause,destroy(){disposed=true;active=false;cancelAnimationFrame(frame);document.removeEventListener('keydown',key);window.removeEventListener('blur',pause);button.onclick=null;board.classList.remove('drill-active');layout.removeAttribute('data-play');}};
 }};
})(window);
