(()=>{
 'use strict';
 const $=id=>document.getElementById(id),id=document.body.dataset.course,M=id==='dolmen'?DolmenMath:id==='airport'?AirportMath:IslandMath,P=IslandProgress,D=IslandTourData,C=D.courses[id],A='asset/island-tour/';
 let state=M.fresh(),saved=null,run=P.status().run,delay=0,photoKey='temple',sound=false,audio=null,play=null;
 const labels={bags:'가방의 출발 기록',belt:'여행을 잇는 연결의 빛',lever:'힘을 모으는 빛',build:'위치를 맞추는 빛',grain:'공양간과 회전의 빛',supply:'좌표와 기울기의 빛',spa:'온천 운영의 빛'};
 const current=()=>C.steps[state.step];
 function stopPlay(){play?.destroy();play=null;}
 function checkRun(){const st=P.status();if(st.run!==run||!st.items.find(c=>c.id===id)?.unlocked){stopPlay();$('main').inert=true;$('lockedText').textContent=st.run!==run?'지역이 초기화되었어요. 월드맵에서 새 여행을 시작해 주세요.':(id==='airport'?'앞선 세 챕터의 빛을 되찾으면 인천국제공항 여행이 열려요.':id==='bomunsa'?'강화고인돌의 빛을 되찾으면 보문사 여행이 열려요.':'보문사의 빛을 되찾으면 석모도 온천 여행이 열려요.');if(!$('locked').open)$('locked').showModal();return false;}return true;}
 function persist(finish=false){if(!P.save(id,state,run,finish))$('saveNotice').hidden=false;}
 function image(el,file,alt){const src=A+file;if(el.getAttribute('src')!==src)el.src=src;el.alt=alt;}
 function busBackground(screen){const bg=C.busBackdrop;image($(screen).querySelector('.backdrop'),bg?.file||C.art+'.webp',bg?.alt||C.title+' 일러스트');}
 function tone(win=true){if(!sound)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(win?620:240,audio.currentTime);o.frequency.exponentialRampToValueAtTime(win?930:190,audio.currentTime+.18);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.36);}catch{}}
 function feedback(text,kind=''){$('feedback').textContent=text;$('game').querySelector('.game-footer').className='game-footer '+kind;}
 function normalize(s){s=M.restore(s);s.step=Math.min(s.step,C.steps.length-1);for(let i=0;i<s.step;i++){const step=C.steps[i];if(step.type==='game'&&!M.solved(s,step.id)){s.step=i;s.line=0;break;}}return s;}
 function go(n,line=0){if(!checkRun())return;clearTimeout(delay);stopPlay();state.step=n;state.line=line;render();persist();}
 function next(){go(Math.min(C.steps.length-1,state.step+1));}
 function render(){stopPlay();const s=current();document.querySelectorAll('main>.screen').forEach(e=>e.hidden=e.id!==s.type);$('main').dataset.screen=s.type;
  if(s.type==='arrival'){busBackground('arrival');$('arrival').querySelector('h1').textContent='이번 정류장은 '+C.title+'입니다.';$('arrival').querySelector('p').textContent='챕터 '+C.number+' · '+C.subtitle+'\n민우와 서연의 영종·강화 수학 여행';$('bus').classList.remove('arriving');void $('bus').offsetWidth;$('bus').classList.add('arriving');$('leaveBus').disabled=true;delay=setTimeout(()=>{$('leaveBus').disabled=false;},1600);$('resume').hidden=!saved;}
  if(s.type==='story')renderStory();
  if(s.type==='photos')renderPhoto();
  if(s.type==='lesson'){const l=D.lessons[s.id];$('lessonTitle').textContent=l.title;$('lessonLead').textContent=l.lead;$('lessonMath').innerHTML=l.math;$('lessonText').textContent=l.text;$('lessonHow').textContent=l.how;$('lessonNote').textContent=l.note;image($('lesson').querySelector('img'),l.art+'.webp',l.lead+' 일러스트');window.DolmenPlay?.lesson($('lesson').querySelector('.lesson-visual'),s.id);}
  if(s.type==='message'){image($('message').querySelector('.backdrop'),C.art+'.webp',C.title+' 일러스트');$('messageTitle').textContent=s.title;$('messageText').textContent=s.text;$('messageNext').textContent=s.button;}
  if(s.type==='game'){$('gameTitle').textContent={bags:'같은 비행기로, 가방을 실어요',belt:'가방의 여행길을 이어요',lever:'거대한 덮개돌을 함께 들어 올려요',build:'설계도대로 고인돌을 세워요',grain:'사용법을 따라, 맷돌 한 바퀴',supply:'민우와 함께 물길을 뚫어요',spa:'노을 온천, 오늘은 우리가 운영자!'}[s.id];$('gameEyebrow').textContent='MISSION '+String(C.missions.indexOf(s.id)+1).padStart(2,'0')+' · '+labels[s.id];play=(id==='dolmen'?DolmenPlay:id==='airport'?AirportPlay:IslandPlay).mount({id:s.id,state,persist,feedback,tone,next,checkRun});}
  if(s.type==='departure'){busBackground('departure');$('departureText').textContent=C.departure||(id==='bomunsa'?'보문사의 빛을 품고 석모도 온천으로 출발합니다.':'세 곳의 빛을 품고 여행을 마무리합니다.');const b=$('departure').querySelector('img.depart-bus');b.style.animation='none';void b.offsetWidth;b.style.animation='';delay=setTimeout(finish,4200);}
  if(s.type==='recap'){image($('recap').querySelector('img'),C.art+'.webp',C.title+'의 빛');$('recapTitle').textContent=C.title+'의 빛을 찾았어요';$('recapText').textContent=C.recap;$('stamps').innerHTML=C.missions.map(k=>'<span>✦ '+labels[k]+'</span>').join('');$('nextChapter').textContent=C.nextId?'챕터 '+D.courses[C.nextId].number+' · '+D.courses[C.nextId].title+' →':'네 곳의 빛 확인 · 월드맵 →';$('nextChapter').href=C.nextId?P.url(C.nextId):P.mapURL;
   $('recap').querySelector('.airport-regional-lights')?.remove();if(id==='airport'&&P.status().items.every(c=>c.completed)){const lights=document.createElement('div');lights.className='airport-regional-lights';lights.innerHTML=[['dolmen-tour/present.webp','강화고인돌'],['island-tour/courtyard.webp','보문사'],['island-tour/onsen.webp','석모도 온천'],['airport-tour/terminal.webp','인천국제공항']].map(([f,n])=>'<figure><img src="asset/'+f+'" alt="'+n+' 일러스트"><figcaption>✦ '+n+'</figcaption></figure>').join('');$('stamps').after(lights);$('recapTitle').textContent='영종·강화, 네 빛이 모였어요';}}
 }
 function renderStory(){const s=current();state.line=Math.min(state.line,s.lines.length-1);const [who,text]=s.lines[state.line];image($('story').querySelector('.backdrop'),s.art+'.webp',s.title+' 일러스트');$('story').classList.toggle('dim',s.dim);$('story').querySelector('.scene-tag').textContent=s.title;$('story').querySelector('.art-credit').textContent=['granary-v2','spa-deck-v2'].includes(s.art)?'관광 자료에서 착안한 창작 체험 일러스트':'실제 장소를 참고한 창작 일러스트';photoKey=s.photo;$('story').querySelector('.real-open').hidden=!photoKey;$('story').classList.toggle('memory-scene',!!s.memory);$('story').classList.toggle('light-found',(id==='dolmen'&&M.solved(state,'build'))||(id==='airport'&&M.solved(state,'belt')));$('story').querySelector('.art-credit').textContent=s.memory?'수첩 속 축조 체험 · 창작 일러스트':$('story').querySelector('.art-credit').textContent;if(s.fiction)$('story').querySelector('.art-credit').textContent='수첩 속 공항 체험 · 창작 일러스트';window.DolmenPlay?.memory($('story'),s.memory,state);$('speaker').textContent=who;$('lineCount').textContent=`${state.line+1} / ${s.lines.length}`;$('lineText').textContent=text;$('storyPrev').disabled=state.line===0;$('storyNext').textContent=state.line===s.lines.length-1?'계속 여행하기 →':'다음 →';$('story').querySelector('.minwoo').classList.toggle('speaking',who==='민우');$('story').querySelector('.seoyeon').classList.toggle('speaking',who==='서연');}
 function renderPhoto(){const s=current();state.line=Math.min(state.line,s.ids.length-1);const p=D.photos[s.ids[state.line]];image($('photoImage'),p.file,p.title+' 실제 사진');$('photoCount').textContent=`${state.line+1} / ${s.ids.length}`;$('photoTitle').textContent=p.title;$('photoText').textContent=p.text;$('photoCredit').textContent='실제 사진 · '+p.credit;$('photoSource').href=p.source;$('photoPrev').disabled=state.line===0;$('photoNext').textContent=state.line===s.ids.length-1?'여행 이어가기 →':'다음 사진 →';}
 function finish(){if(current().type!=='departure'||!C.missions.every(g=>M.solved(state,g)))return;state.departed=true;persist(true);next();}
 $('storyNext').onclick=()=>{if(state.line<current().lines.length-1){state.line++;renderStory();persist();}else next();};$('storyPrev').onclick=()=>{if(state.line){state.line--;renderStory();persist();}};
 $('photoNext').onclick=()=>{if(state.line<current().ids.length-1){state.line++;renderPhoto();persist();}else next();};$('photoPrev').onclick=()=>{if(state.line){state.line--;renderPhoto();persist();}};
 $('messageNext').onclick=next;$('leaveBus').onclick=()=>next();$('resume').onclick=()=>{if(!saved)return;state=normalize(saved);saved=null;render();persist();};$('begin').onclick=next;$('finishDeparture').onclick=finish;
 $('story').querySelector('.real-open').onclick=()=>{const p=D.photos[photoKey];if(!p)return;$('realTitle').textContent=p.title;image($('realImage'),p.file,p.title);$('realCaption').textContent=p.credit;$('realSource').href=p.source;$('photoDialog').showModal();};
 $('help').onclick=()=>{play?.pause();const l=D.lessons[current().id==='grain'&&state.grain.loaded?'mill':current().id];$('helpTitle').textContent=l.title;$('helpMath').innerHTML=l.math;$('helpText').textContent=l.text;$('helpHow').textContent=l.how;$('helpDialog').showModal();};
 $('journal').onclick=()=>{play?.pause();$('noteBody').innerHTML='<p>학생 원안 · '+C.student+'</p><p>'+C.missions.map(g=>(M.solved(state,g)?'✦ ':'○ ')+labels[g]).join('　')+'</p><p>실제 장소를 둘러보며 생활 속 수학의 빛을 찾아요.</p><p style="font-size:13px">'+(C.journal|| (id==='bomunsa'?'장은성 학생의 맷돌·418계단·마애불 여행을 살렸어요. 3칸·5칸 통으로 곡식 4칸을 만들어 맷돌에 넣고, 사용법을 얻은 뒤 원안의 네 식을 풀어 60°·90°·120°·90°를 이어 돌려요.':'김주원 학생의 온천 배관·좌표·일차함수 문제를 물 공급 단계에 살리고, 이어서 물의 양과 변화율로 온천을 운영해요.'))+'</p>';$('note').showModal();};
 $('restartOpen').onclick=()=>{$('note').close();$('restartDialog').showModal();};$('restart').onclick=()=>{$('restartDialog').close();state=M.fresh();saved=null;go(0);};
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('sound').setAttribute('aria-pressed',sound);if(sound)tone();};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('locked').addEventListener('cancel',e=>e.preventDefault());
 window.addEventListener('mathtour:island-progress',checkRun);document.addEventListener('visibilitychange',()=>{if(document.hidden)play?.pause();else checkRun();});window.addEventListener('pagehide',()=>{play?.pause();if(state.step>0&&checkRun())persist();});
 if(!checkRun())return;const old=P.load(id);if((old?.version===2||old?.version==='dolmen-1'||old?.version==='airport-1')&&old.step>0)saved=normalize(old);render();
})();

