(()=>{
 'use strict';
 const $=id=>document.getElementById(id),M=IslandMath,P=IslandProgress,D=IslandTourData,id=document.body.dataset.course,C=D.courses[id],A='asset/island-tour/';
 let state=M.fresh(),saved=null,run=P.status().run,selected=0,point={x:0,y:0},chosenSlope=null,busy=false,delay=0,photoKey='temple',sound=false,audio=null;
 const labels={mill:'회전의 빛',stairs:'기울기의 빛',halo:'닮음의 빛',coords:'좌표의 빛',pipes:'물길의 빛'};
 const current=()=>C.steps[state.step];
 function checkRun(){const st=P.status();if(st.run!==run||!st.items.find(c=>c.id===id)?.unlocked){$('main').inert=true;$('lockedText').textContent=st.run!==run?'지역이 초기화되었어요. 월드맵에서 새 여행을 시작해 주세요.':'보문사의 빛을 되찾으면 석모도 온천 여행이 열려요.';if(!$('locked').open)$('locked').showModal();return false;}return true;}
 function persist(finish=false){if(!P.save(id,state,run,finish))$('saveNotice').hidden=false;}
 function image(el,file,alt){const src=A+file;if(el.getAttribute('src')!==src)el.src=src;el.alt=alt;}
 function tone(win=true){if(!sound)return;try{audio ||=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(win?620:240,audio.currentTime);o.frequency.exponentialRampToValueAtTime(win?930:190,audio.currentTime+.18);g.gain.setValueAtTime(.06,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.35);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.36);}catch{}}
 function feedback(text,kind=''){ $('feedback').textContent=text;$('game').querySelector('.game-footer').className='game-footer '+kind;}
 function showScreen(name){document.querySelectorAll('main>.screen').forEach(e=>e.hidden=e.id!==name);document.querySelector('main').dataset.screen=name;}
 function normalize(s){s=M.restore(s);s.step=Math.min(s.step,C.steps.length-1);for(let i=0;i<s.step;i++){const step=C.steps[i];if(step.type==='game'&&!M.solved(s,step.id)){s.step=i;s.line=0;break;}}return s;}
 function go(n,line=0){if(!checkRun())return;clearTimeout(delay);busy=false;state.step=n;state.line=line;render();persist();}
 function next(){go(Math.min(C.steps.length-1,state.step+1));}
 function render(){const s=current();showScreen(s.type);if(s.type==='arrival'){image($('arrival').querySelector('.backdrop'),C.art+'.webp',C.title+' 일러스트');$('arrival').querySelector('h1').textContent='이번 정류장은 '+C.title+'입니다.';$('arrival').querySelector('p').textContent='챕터 '+C.number+' · '+C.subtitle+'\n민우와 서연의 영종·강화 수학 여행';$('bus').classList.remove('arriving');void $('bus').offsetWidth;$('bus').classList.add('arriving');$('leaveBus').disabled=true;delay=setTimeout(()=>{$('leaveBus').disabled=false;},1600);$('resume').hidden=!saved;}
  if(s.type==='story')renderStory();
  if(s.type==='photos')renderPhoto();
  if(s.type==='lesson'){const l=D.lessons[s.id];$('lessonTitle').textContent=l.title;$('lessonLead').textContent=l.lead;$('lessonMath').innerHTML=l.math;$('lessonText').textContent=l.text;$('lessonHow').textContent=l.how;image($('lesson').querySelector('img'),l.art+'.webp',l.lead+' 일러스트');}
  if(s.type==='game'){selected=s.id==='halo'?(state.halo?1.5:1):s.id==='stairs'&&M.solved(state,'stairs')?state.stairs.at(-1):0;point=s.id==='pipes'?{...(state.pipes.at(-1)||M.source)}:{x:0,y:0};chosenSlope=null;renderGame();}
  if(s.type==='departure'){image($('departure').querySelector('.backdrop'),C.art+'.webp',C.title+' 일러스트');$('departureText').textContent=id==='bomunsa'?'보문사의 빛을 품고 석모도 온천으로 출발합니다.':'온천의 빛을 품고 영종도로 이어질 다음 여행을 준비합니다.';const b=$('departure').querySelector('img.depart-bus');b.style.animation='none';void b.offsetWidth;b.style.animation='';delay=setTimeout(finish,4200);}
  if(s.type==='recap'){image($('recap').querySelector('img'),C.art+'.webp',C.title+'의 빛');$('recapTitle').textContent=C.title+'의 빛을 찾았어요';$('recapText').textContent=id==='bomunsa'?'맷돌의 회전, 계단의 기울기, 같은 모양의 닮음. 세 단서로 보문사의 풍경이 밝아졌어요.':'풍경의 좌표를 찾고, 기울기로 배관을 연결했어요. 온천에 물과 빛이 돌아왔어요.';$('stamps').innerHTML=C.missions.map(k=>'<span>✦ '+labels[k]+'</span>').join('');$('nextChapter').textContent=id==='bomunsa'?'챕터 2 · 온천으로 →':'다음 여행 준비 · 월드맵 →';$('nextChapter').href=id==='bomunsa'?P.url('seokmodo'):P.mapURL;}
 }
 function renderStory(){const s=current();state.line=Math.min(state.line,s.lines.length-1);const [who,text]=s.lines[state.line];image($('story').querySelector('.backdrop'),s.art+'.webp',s.title+' 일러스트');$('story').classList.toggle('dim',s.dim);$('story').querySelector('.scene-tag').textContent=s.title;photoKey=s.photo;$('speaker').textContent=who;$('lineCount').textContent=`${state.line+1} / ${s.lines.length}`;$('lineText').textContent=text;$('storyPrev').disabled=state.line===0;$('storyNext').textContent=state.line===s.lines.length-1?'계속 여행하기 →':'다음 →';$('story').querySelector('.minwoo').classList.toggle('speaking',who==='민우');$('story').querySelector('.seoyeon').classList.toggle('speaking',who==='서연');}
 function renderPhoto(){const s=current();state.line=Math.min(state.line,s.ids.length-1);const p=D.photos[s.ids[state.line]];image($('photoImage'),p.file,p.title+' 실제 사진');$('photoCount').textContent=`${state.line+1} / ${s.ids.length}`;$('photoTitle').textContent=p.title;$('photoText').textContent=p.text;$('photoCredit').textContent='실제 사진 · '+p.credit;$('photoSource').href=p.source;$('photoPrev').disabled=state.line===0;$('photoNext').textContent=state.line===s.ids.length-1?'여행 이어가기 →':'다음 사진 →';}
 function svg(body,vb='0 0 600 480'){return '<svg viewBox="'+vb+'" xmlns="http://www.w3.org/2000/svg" aria-label="'+D.lessons[current().id].lead+'" role="img">'+body+'</svg>';}
 const text=(x,y,s,fill='#fff2cb',size=18,extra='')=>`<text x="${x}" y="${y}" text-anchor="middle" fill="${fill}" font-size="${size}" ${extra}>${s}</text>`;
 function backdrop(art){return `<image href="${A+art}.webp" width="600" height="480" preserveAspectRatio="xMidYMid slice" opacity=".45"/><rect width="600" height="480" fill="#102e3f" opacity=".35"/>`;}
 function arc(cx,cy,r,start,end){const p=a=>[cx+r*Math.sin(a*Math.PI/180),cy-r*Math.cos(a*Math.PI/180)];const a=p(start),b=p(end);if(end-start>=359.9)return `<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#ffd46e" stroke-width="13"/>`;return `<path d="M ${a.join(' ')} A ${r} ${r} 0 ${end-start>180?1:0} 1 ${b.join(' ')}" fill="none" stroke="#ffd46e" stroke-width="13" stroke-linecap="round"/>`;}
 function millBoard(){const done=state.mill.reduce((a,b)=>a+b,0),a=selected+done;let ticks='';for(let n=0;n<360;n+=30){const r=n*Math.PI/180,x=300+190*Math.sin(r),y=230-190*Math.cos(r);ticks+=text(x,y+6,n+'°','#ffe5a6',14);}return svg(backdrop('courtyard')+`<defs><radialGradient id="stone"><stop stop-color="#b9b9a6"/><stop offset=".65" stop-color="#898d80"/><stop offset="1" stop-color="#515e55"/></radialGradient><pattern id="speck" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="5" cy="8" r="1.3" fill="#e7e3cd"/><circle cx="15" cy="16" r="1" fill="#535d54"/></pattern></defs><ellipse cx="300" cy="277" rx="176" ry="156" fill="#282f2c"/><circle cx="300" cy="230" r="163" fill="url(#stone)" stroke="#d7cfad" stroke-width="4"/><circle cx="300" cy="230" r="157" fill="url(#speck)" opacity=".65"/>`+ticks+arc(300,230,174,0,Math.max(.01,done))+arc(300,230,145,done,Math.max(done+.01,a))+`<g transform="rotate(${a} 300 230)"><path d="M300 230V103" stroke="#d6bc85" stroke-width="10"/><rect x="287" y="85" width="26" height="65" rx="11" fill="#9b6841" stroke="#eacfa1" stroke-width="3"/></g><circle cx="300" cy="230" r="24" fill="#1f3738" stroke="#eee4b9" stroke-width="5"/>`+text(300,450,'현재 '+selected+'° · 모은 회전 '+done+'°','#fff1c5',20));}
 function grid(ymin=0){let h='<rect x="58" y="48" width="470" height="380" rx="10" fill="#112d39" opacity=".82"/>';for(let i=0;i<=10;i++){const x=70+i*44,y=410-i*34;h+=`<path d="M${x} 70V410 M70 ${y}H510" stroke="#a5c4c4" opacity=".24" stroke-width="1"/>`;h+=text(x,442,i,'#eaf2d9',14)+text(42,y+5,i+ymin,'#eaf2d9',14);}h+=text(538,421,'x','#f9d37a',22,'class="math-label"')+text(66,43,'y','#f9d37a',22,'class="math-label"');return h;}
 const gx=x=>70+x*44,gy=y=>410-y*34,py=y=>gy(y+10);
 function stairBoard(){const q=M.stairs[Math.min(state.stairs.length,2)],a=selected,limit=a>0?Math.min(9,(10-q.b)/a):9;let stair='';if(a>0)for(let x=0;x<limit-.25;x+=.5){const xx=Math.min(limit,x+.5);stair+=`M${gx(x)},${gy(q.b+a*x)}H${gx(xx)}V${gy(q.b+a*xx)}`;}return svg(backdrop('courtyard')+grid()+`<path d="${stair}" stroke="#d2ba83" stroke-width="5" fill="none"/><path d="M${gx(0)} ${gy(q.b)}L${gx(limit)} ${gy(q.b+a*limit)}" stroke="#ffcf5c" stroke-width="4" fill="none"/><circle cx="70" cy="${gy(q.b)}" r="10" fill="#6fddc0"/>`+text(gx(q.x),gy(q.y)+8,'✦','#ffda69',35)+text(gx(q.x),gy(q.y)-23,`(${q.x}, ${q.y})`,'#fff5d0',17)+text(300,24,'계단을 잇는 빛 · '+Math.min(state.stairs.length+1,3)+' / 3','#fff4d0',18));}
 function haloBoard(){const f=selected;return svg(backdrop('maae')+`<ellipse cx="300" cy="220" rx="135" ry="180" stroke="#baf4ec" stroke-dasharray="9 9" stroke-width="4" fill="none"/><ellipse cx="300" cy="220" rx="${90*f}" ry="${120*f}" fill="#ffe391" fill-opacity=".16" stroke="#ffd673" stroke-width="6"/><ellipse cx="300" cy="220" rx="90" ry="120" fill="none" stroke="#fff9d8" stroke-opacity=".5" stroke-width="2"/>`+text(300,220,'✦','#ffe2a0',44)+text(300,450,`가로 ${M.format(6*f)}칸 · 세로 ${M.format(8*f)}칸`,'#fff7d9',22)+text(300,28,'점선에 빛을 겹쳐요 · 수첩 속 닮음 모형','#e9ffed',16));}
 function coordinateBoard(){const points=M.coordinates;let h=backdrop('onsen')+grid();for(let i=0;i<points.length;i++){const p=points[i],done=state.coords.some(q=>M.same(q,p));h+=`<circle cx="${gx(p.x)}" cy="${gy(p.y)}" r="${done?26:21}" fill="${done?'#f7d571':'#dfceba'}" opacity=".8"/>`+(i===0?`<g transform="translate(${gx(p.x)} ${gy(p.y)})"><ellipse cx="-13" cy="3" rx="16" ry="10" fill="#f8d2db"/><ellipse cx="2" cy="-4" rx="19" ry="14" fill="#fff1ed"/><ellipse cx="17" cy="4" rx="15" ry="10" fill="#f8d2db"/></g>`:i===1?`<path d="M${gx(p.x)-25} ${gy(p.y)}q12 -19 25 0q13 -19 25 0" stroke="#ffffed" stroke-width="6" fill="none" stroke-linecap="round"/>`:text(gx(p.x),gy(p.y)+7,'✦','#fff1be',32));}h+=`<circle cx="${gx(point.x)}" cy="${gy(point.y)}" r="25" fill="none" stroke="#85f4d8" stroke-width="4"/>`+text(300,25,'터치로 위치 선택 · (가로, 세로)','#fff4d4',18);return svg(h);}
 function pipeBoard(){const reached=M.pipeProgress(state.pipes),p=state.pipes.at(-1)||M.source;let h=`<defs><linearGradient id="earth" x2="0" y2="1"><stop stop-color="#b9975f"/><stop offset=".55" stop-color="#75786a"/><stop offset="1" stop-color="#414c54"/></linearGradient></defs><rect width="600" height="480" fill="url(#earth)"/><rect width="600" height="70" fill="#8daf82"/>`+grid(-10);M.obstacles.forEach(r=>h+=`<rect x="${gx(r.x)}" y="${py(r.y+r.h)}" width="${r.w*44}" height="${r.h*34}" rx="17" fill="#73796e" stroke="#bbc5aa" stroke-width="3"/>`+text(gx(r.x+r.w/2),py(r.y+r.h/2)+5,'바위','#f8f2d9',16));let prev=M.source;state.pipes.forEach(q=>{h+=`<path d="M${gx(prev.x)} ${py(prev.y)}L${gx(q.x)} ${py(q.y)}" stroke="#dbab66" stroke-width="15" fill="none" stroke-linecap="round"/><path class="trace" d="M${gx(prev.x)} ${py(prev.y)}L${gx(q.x)} ${py(q.y)}" stroke="#a8f1ee" stroke-width="6" fill="none"/>`;prev=q;});if(!M.same(point,p)&&chosenSlope!==null){const endY=p.y+chosenSlope*(point.x-p.x);h+=`<path d="M${gx(p.x)} ${py(p.y)}L${gx(point.x)} ${py(endY)}" stroke="#ffe5a3" stroke-dasharray="9 7" stroke-width="6" fill="none"/>`;}
  M.valves.forEach((v,i)=>{h+=`<circle cx="${gx(v.x)}" cy="${py(v.y)}" r="23" fill="${i<reached?'#d1ffae':i===reached?'#ffe49c':'#d6d1ba'}" stroke="#614c2e" stroke-width="3"/>`+text(gx(v.x),py(v.y)+6,i===2?'♨':i+1,'#294449',19);});h+=`<circle cx="${gx(M.source.x)}" cy="${py(M.source.y)}" r="17" fill="#89d9e1"/><circle cx="${gx(p.x)}" cy="${py(p.y)}" r="28" fill="none" stroke="#b9ffdc" stroke-width="4"/><circle cx="${gx(point.x)}" cy="${py(point.y)}" r="14" fill="none" stroke="#ffffff" stroke-width="3"/>`+text(300,28,'지표면 · 온천','#f5ffe6',16)+text(300,472,'−10칸 = 지하 460m · 체험용 배관 모형','#fff2c5',14);return svg(h);}
 function choice(values,chosen,unit='',attr='value'){return '<div class="choices">'+values.map(v=>`<button data-${attr}="${v}" aria-pressed="${chosen===v}">${M.format(v)}${unit}</button>`).join('')+'</div>';}
 function dpad(){return '<div class="dpad"><button data-move="0,1" aria-label="위로 한 칸">↑</button><button data-move="-1,0" aria-label="왼쪽으로 한 칸">←</button><button data-move="0,-1" aria-label="아래로 한 칸">↓</button><button data-move="1,0" aria-label="오른쪽으로 한 칸">→</button></div>';}
 function renderGame(keepFeedback=false){const g=current().id,complete=M.solved(state,g),q=Math.min(state[g]?.length||0,g==='mill'?3:2);$('gameTitle').textContent={mill:'맷돌의 네 번 회전',stairs:'계단을 따라 빛의 길 잇기',halo:'같은 모양으로 빛 모으기',coords:'노을 속 빛의 좌표 찾기',pipes:'온천으로 이어지는 물길'}[g];$('gameEyebrow').textContent='MISSION '+String(C.missions.indexOf(g)+1).padStart(2,'0')+' · '+labels[g];
  $('board').innerHTML=({mill:millBoard,stairs:stairBoard,halo:haloBoard,coords:coordinateBoard,pipes:pipeBoard}[g])();
  let controls='';if(g==='mill'){const equations=['3<i>x</i> = 180°','2<i>x</i> + 30° = 210°','<i>x</i> ÷ 2 = 60°','360°의 1/4'];controls=`<h2>${Math.min(q+1,4)}번째 회전</h2><div class="math">${equations[q]}</div><p>이번에 돌릴 각 <i>x</i>는 얼마일까요?</p>`+choice([30,60,90,120],selected,'°')+`<div class="adjust"><button data-angle="-15" aria-label="15도 줄이기">−</button><output>${selected}°</output><button data-angle="15" aria-label="15도 늘리기">＋</button></div><p class="small">시계 방향으로 돌려요. 네 회전의 합이 한 바퀴가 되어야 해요.</p>`;}
  if(g==='stairs'){const t=M.stairs[q];controls=`<h2>출발 높이 ${t.b} → 별 (${t.x}, ${t.y})</h2><div class="math"><i>y</i> = <i>a x</i> + ${t.b}</div><p>오른쪽 ${t.x}칸, 위로 ${t.y-t.b}칸.<br>기울기 <i>a</i>를 골라요.</p>`+choice([.5,1,1.5,2],selected)+`<p class="small">기울기 = 높이 변화 ÷ 가로 변화<br>실제 계단을 단순하게 나타낸 수첩 모형이에요.</p>`;}
  if(g==='halo')controls='<h2>원래 : 확대 = 2 : 3</h2><div class="math">가로 6칸 → 9칸</div><p>가로와 세로를 같은 배율로 키워요.</p>'+choice([.5,1,1.5,2],selected,'배')+'<p>현재 세로: <strong>'+M.format(8*selected)+'칸</strong></p><p class="small">광배에서 떠올린 빛의 모형이에요.<br>칸 수는 실제 불상의 치수가 아니에요.</p>';
  if(g==='coords'){const t=M.coordinates[q];controls=`<h2>${t.name}의 빛 찾기</h2><div class="math">목표 (${t.x}, ${t.y})</div><p>선택한 곳: <strong>(${point.x}, ${point.y})</strong></p>`+dpad()+'<p class="small">가로 먼저, 세로 다음. 격자점도 직접 누를 수 있어요.</p>';}
  if(g==='pipes'){const n=M.pipeProgress(state.pipes),p=state.pipes.at(-1)||M.source,v=M.valves[Math.min(n,2)],a=M.slope(p,point),options=[-2,-1,.5,1,2];if(a!==null&&Number.isFinite(a)&&!options.some(x=>M.eq(x,a))&&!M.same(point,p))options.push(a);controls=`<h2>${n<2?n+1+'번 밸브':'온천'} (${v.x}, ${v.y})</h2><p>현재 (${p.x}, ${p.y}) → 선택 (${point.x}, ${point.y})</p><p class="small">① 격자점 선택　② 기울기 선택</p>`+choice(options,chosenSlope,'','slope')+`<div class="math" style="font-size:21px"><i>y</i> = ${chosenSlope===null?'?':M.format(chosenSlope)}<i>x</i>${chosenSlope===null?' + ?':(p.y-chosenSlope*p.x<0?' − ':' + ')+M.format(Math.abs(p.y-chosenSlope*p.x))}</div><div class="micro-actions"><button id="pipeUndo" ${!state.pipes.length?'disabled':''}>한 연결 되돌리기</button><button id="pipeHint">힌트 보기</button></div><p class="small">연결 ${state.pipes.length} / 6 · 오류는 배관을 소모하지 않아요.</p>`;}
  $('controls').innerHTML=controls;$('confirm').disabled=false;$('confirm').textContent=complete?'다음 이야기 →':g==='coords'?'풍경 찾기':g==='pipes'?'배관 연결':'빛 맞추기';
  if(complete){$('controls').innerHTML='<h2>✦ '+labels[g]+' 완성!</h2><p>'+{mill:'60° + 90° + 120° + 90° = 360°. 한 바퀴를 완성했어요.',stairs:'기울기는 높이 변화 ÷ 가로 변화. 세 빛의 길이 모두 이어졌어요.',halo:'6 → 9, 8 → 12. 대응하는 길이를 모두 3/2배 했어요.',coords:'가로 위치 x, 세로 위치 y. 세 풍경의 좌표를 정확히 찾았어요.',pipes:'직선의 기울기를 정해 두 밸브를 지나 온천까지 물길을 이었어요.'}[g]+'</p><div class="math">'+labels[g]+' ✦</div>';feedback('잘했어요! 수첩에 빛이 모였어요.','good');return;}
  if(!keepFeedback)feedback(g==='pipes'?'초록 테두리가 현재 위치예요. 다음 연결 지점을 눌러요.':'그림을 조작하고 아래 버튼으로 확인해요.');
  $('controls').querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.value);renderGame();});$('controls').querySelectorAll('[data-slope]').forEach(b=>b.onclick=()=>{chosenSlope=Number(b.dataset.slope);renderGame();});$('controls').querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>{selected=Math.max(0,Math.min(180,selected+Number(b.dataset.angle)));renderGame();});
  $('controls').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const [x,y]=b.dataset.move.split(',').map(Number);point={x:Math.max(0,Math.min(10,point.x+x)),y:Math.max(0,Math.min(10,point.y+y))};renderGame();});
  const surface=$('board').querySelector('svg');surface.addEventListener('pointerdown',e=>{if(!['mill','coords','pipes'].includes(g)||busy)return;const p=surface.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform(surface.getScreenCTM().inverse());if(g==='mill'){const deg=(Math.atan2(v.x-300,230-v.y)*180/Math.PI+360)%360,done=state.mill.reduce((a,b)=>a+b,0);selected=Math.min(180,Math.round(((deg-done+360)%360)/15)*15);}else{if(v.x<48||v.x>532||v.y<48||v.y>432)return;point={x:Math.max(0,Math.min(10,Math.round((v.x-70)/44))),y:Math.max(0,Math.min(10,Math.round((410-v.y)/34)))-(g==='pipes'?10:0)};chosenSlope=null;}renderGame();});
  if(g==='pipes'){$('pipeUndo').onclick=()=>{state.pipes.pop();point={...(state.pipes.at(-1)||M.source)};chosenSlope=null;persist();renderGame();};$('pipeHint').onclick=()=>{const p=state.pipes.at(-1)||M.source,v=M.valves[Math.min(M.pipeProgress(state.pipes),2)];feedback(`다음 목표는 (${v.x}, ${v.y}). 목표를 누른 뒤, 높이 변화 ÷ 가로 변화 = (${v.y} − (${p.y})) ÷ (${v.x} − ${p.x})를 생각해 보세요.`);};}
 }
 function submit(){if(busy||!checkRun())return;const g=current().id;if(M.solved(state,g)){next();return;}let error='';
  if(g==='mill'){if(selected!==M.mill[state.mill.length])error='식을 만족하는 각도를 다시 생각해 봐요. 개념 안내도 열어볼 수 있어요.';else state.mill.push(selected);}
  if(g==='stairs'){if(selected!==M.stairs[state.stairs.length].a)error='빛이 별을 지나지 않아요. 높이 변화를 오른쪽으로 간 칸 수로 나눠 보세요.';else state.stairs.push(selected);}
  if(g==='halo'){if(selected!==1.5)error='가로 6칸이 9칸이 되는 배율을 찾아요. 세로도 같은 배율로 바뀌어야 해요.';else state.halo={width:9,height:12};}
  if(g==='coords'){if(!M.same(point,M.coordinates[state.coords.length]))error='목표의 첫 수는 가로, 두 번째 수는 세로예요. 선택한 위치를 다시 살펴봐요.';else state.coords.push({...point});}
  if(g==='pipes'){const p=state.pipes.at(-1)||M.source;error=M.inspectPipe(p,point,chosenSlope);if(!error&&state.pipes.length>=6)error='배관 여섯 개를 모두 썼어요. 한 연결 되돌리기로 길을 다시 정해요.';if(!error)state.pipes.push({...point});}
  if(error){tone(false);feedback(error,'bad');return;}tone();persist();selected=g==='halo'?1.5:g==='stairs'&&M.solved(state,'stairs')?state.stairs.at(-1):0;chosenSlope=null;if(g==='coords')point={x:0,y:0};renderGame();if(!M.solved(state,g))feedback(g==='pipes'?'배관이 이어졌어요! 다음 밸브로 길을 계속 이어요.':'정확해요! 다음 단서도 이어서 찾아봐요.','good');const flare=document.createElement('div');flare.className='success-flare';$('board').append(flare);
 }
 function finish(){if(current().type!=='departure'||!C.missions.every(g=>M.solved(state,g)))return;state.departed=true;persist(true);next();}
 $('storyNext').onclick=()=>{if(state.line<current().lines.length-1){state.line++;renderStory();persist();}else next();};$('storyPrev').onclick=()=>{if(state.line){state.line--;renderStory();persist();}};
 $('photoNext').onclick=()=>{if(state.line<current().ids.length-1){state.line++;renderPhoto();persist();}else next();};$('photoPrev').onclick=()=>{if(state.line){state.line--;renderPhoto();persist();}};
 $('leaveBus').onclick=()=>next();$('resume').onclick=()=>{if(!saved)return;state=normalize(saved);saved=null;render();persist();};$('begin').onclick=next;$('confirm').onclick=submit;$('finishDeparture').onclick=finish;
 $('story').querySelector('.real-open').onclick=()=>{const p=D.photos[photoKey];$('realTitle').textContent=p.title;image($('realImage'),p.file,p.title);$('realCaption').textContent=p.credit;$('realSource').href=p.source;$('photoDialog').showModal();};
 $('help').onclick=()=>{const l=D.lessons[current().id];$('helpTitle').textContent=l.title;$('helpMath').innerHTML=l.math;$('helpText').textContent=l.text;$('helpHow').textContent=l.how;$('helpDialog').showModal();};
 $('journal').onclick=()=>{$('noteBody').innerHTML='<p>학생 원안 · '+C.student+'</p><p>'+C.missions.map(g=>(M.solved(state,g)?'✦ ':'○ ')+labels[g]).join('　')+'</p><p>실제 장소를 둘러보며 수첩 속 수학의 빛을 찾아요.</p><p style="font-size:13px">원안의 '+(id==='bomunsa'?'맷돌·계단·마애불과 수학의 빛 이야기':'온천 배관 설계·노을 좌표 찾기 아이디어')+'를 바탕으로 구성했어요.</p>';$('note').showModal();};
 $('restartOpen').onclick=()=>{$('note').close();$('restartDialog').showModal();};$('restart').onclick=()=>{$('restartDialog').close();state=M.fresh();saved=null;go(0);};
 $('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'소리 켜짐':'소리 꺼짐';$('sound').setAttribute('aria-pressed',sound);if(sound)tone();};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('locked').addEventListener('cancel',e=>e.preventDefault());
 window.addEventListener('mathtour:island-progress',checkRun);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkRun();});window.addEventListener('pagehide',()=>{if(state.step>0&&checkRun())persist();});
 // Buttons support Enter/Space natively. Arrow keys additionally move the coordinate cursor.
 window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||current().type!=='game'||!['coords','pipes'].includes(current().id)||M.solved(state,current().id))return;const d={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,1],ArrowDown:[0,-1]}[e.key];if(!d)return;e.preventDefault();const bottom=current().id==='pipes'?-10:0;point={x:Math.max(0,Math.min(10,point.x+d[0])),y:Math.max(bottom,Math.min(bottom+10,point.y+d[1]))};chosenSlope=null;renderGame();});
 if(!checkRun())return;saved=P.load(id);if(saved)saved=normalize(saved);render();
})();
