(function(root){
 'use strict';
 const M=root.AirportMath;
 const sprite=(kind,cls='')=>'<span class="airport-luggage '+(kind==='y'?'gold':'blue')+' '+cls+'" aria-hidden="true"></span>';
 function mount({id,state,persist,feedback,tone,next,checkRun}){
  const board=document.getElementById('board'),controls=document.getElementById('controls'),confirm=document.getElementById('confirm'),game=document.getElementById('game'),s=state[id],t=M.specs[id],bags=id==='bags';
  let running=false,paused=false,dead=false,elapsed=0,last=0,raf=0,hint=0;
  game.classList.add('airport-game');
  board.innerHTML='<img class="airport-game-bg" src="asset/airport-tour/bhs.webp" alt="수첩 속 공항 수하물 센터 일러스트"><div class="airport-record"><small>빛의 수첩 · '+(bags?'가방의 출발 기록':'마지막 운송 기록')+'</small><strong>'+(bags?'가방 8개 · 총 160kg':'10초 동안 · 16m 이동')+'</strong></div><div class="airport-checks"><div data-check="total"></div><div data-check="result"></div></div>'+(bags?'<div class="airport-load-area"><div class="airport-empty">＋ 버튼으로 가방을 실어요</div><div class="airport-cargo"></div><div class="airport-platform">출발 대기 · 같은 항공편의 가방</div></div>':'<div class="airport-route"><div class="airport-route-status" role="status">시간을 정하고 운송을 시작해요.</div><div class="airport-track"><div class="airport-fast"></div><div class="airport-slow"></div><div class="airport-goal"><span>도착 16m</span></div><div class="airport-moving">'+sprite('x')+'</div></div><div class="airport-ruler"><span>0m · 출발</span><span>8m</span><span>16m</span><span>24m</span><span>32m</span></div></div>')+'<small class="airport-model-note">수첩 속 체험용 운송 모형</small>';
  controls.innerHTML='<div class="airport-control-intro"><small>'+(bags?'가방을 눌러 실어요':'두 벨트의 시간을 정해요')+'</small><strong>'+(bags?'개수와 무게를 함께 확인!':'이동 거리 = 속력 × 시간')+'</strong></div>'+['x','y'].map(k=>'<section class="airport-selector '+k+'"><div class="airport-select-label">'+sprite(k)+'<div><strong>'+(bags?(k==='x'?'파란 가방':'노란 가방'):(k==='x'?'빠른 벨트':'느린 벨트'))+'</strong><small>'+(bags?(k==='x'?'한 개 15kg':'한 개 35kg'):(k==='x'?'1초에 2m 이동':'1초에 1m 이동'))+'</small></div></div><div class="airport-stepper"><button data-key="'+k+'" data-delta="-1" aria-label="'+(bags?(k==='x'?'파란 가방':'노란 가방'):(k==='x'?'빠른 벨트':'느린 벨트'))+' 줄이기">−</button><output data-value="'+k+'"></output><button data-key="'+k+'" data-delta="1" aria-label="'+(bags?(k==='x'?'파란 가방':'노란 가방'):(k==='x'?'빠른 벨트':'느린 벨트'))+' 늘리기">＋</button></div></section>').join('')+'<div class="airport-equations math"></div><div class="airport-tools"><button class="airport-hint">생각의 힌트</button><button class="airport-reset">처음 값으로</button></div>';
  const modal=()=>document.hidden||!!document.querySelector('dialog[open]');
  const won=()=>M.solved(state,id);
  function sync(){
   const q=M.inspect(id,s.x,s.y),locked=running||won();
   for(const k of ['x','y']){controls.querySelector('[data-value='+k+']').textContent=s[k]+(bags?'개':'초');controls.querySelectorAll('[data-key='+k+']').forEach(b=>{b.disabled=locked||(Number(b.dataset.delta)<0?s[k]===0:s[k]===t.max);});}
   const c=board.querySelector('[data-check=total]'),v=board.querySelector('[data-check=result]');
   c.className=q.countOK?'matched':'';v.className=q.valueOK?'matched':'';
   c.innerHTML='<small>'+(bags?'현재 개수':'계획한 시간')+'</small><strong>'+q.total+(bags?'개':'초')+' / '+t.total+(bags?'개':'초')+'</strong><span>'+(q.countOK?'✓ 일치':'조절해요')+'</span>';
   v.innerHTML='<small>'+(bags?'현재 무게':'계획한 거리')+'</small><strong>'+q.result+(bags?'kg':'m')+' / '+t.result+(bags?'kg':'m')+'</strong><span>'+(q.valueOK?'✓ 일치':'조절해요')+'</span>';
   controls.querySelector('.airport-equations').innerHTML=bags?s.x+' + '+s.y+' = '+q.total+'개<br>15 × '+s.x+' + 35 × '+s.y+' = '+q.result+'kg':s.x+' + '+s.y+' = '+q.total+'초<br>2 × '+s.x+' + 1 × '+s.y+' = '+q.result+'m';
   controls.querySelector('.airport-reset').disabled=won();controls.querySelector('.airport-hint').disabled=running||won();
   board.classList.toggle('airport-won',won());
   confirm.disabled=false;confirm.textContent=won()?'여행 이어가기 →':running?(paused?'운송 계속 →':'잠깐 멈추기'):(bags?'수하물 보내기 →':'운송 시작 →');
   if(bags){const cargo=board.querySelector('.airport-cargo');if(!running&&!won()){cargo.style.transform='';cargo.style.opacity='';}cargo.innerHTML=['x','y'].map(k=>Array.from({length:s[k]},()=>'<button data-remove="'+k+'" aria-label="'+(k==='x'?'파란':'노란')+' 가방 하나 내리기" '+(locked?'disabled':'')+'>'+sprite(k)+'</button>').join('')).join('');board.querySelector('.airport-empty').hidden=q.total>0;board.querySelector('.airport-platform').textContent=won()?'✓ 출발 기록 복원 · 운송 완료':running?'가방을 운송하고 있어요':'출발 대기 · 가방을 누르면 다시 내려요';}
  }
  function edit(k,delta){if(dead||running||won()||modal()||!checkRun())return;s[k]=Math.max(0,Math.min(t.max,s[k]+delta));elapsed=0;hint=0;sync();if(!bags)drawRoute();feedback(bags?'개수와 무게, 두 표시가 모두 일치하도록 맞춰 주세요.':'빠른 벨트와 느린 벨트의 이용 시간을 정해 주세요.');persist();}
  controls.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>edit(b.dataset.key,Number(b.dataset.delta)));
  board.onclick=e=>{const b=e.target.closest('[data-remove]');if(b)edit(b.dataset.remove,-1);};
  controls.querySelector('.airport-hint').onclick=()=>{if(!checkRun()||running)return;const hints=bags?['8개를 모두 파란 가방으로 싣는다면 무게가 얼마일까요?','파란 가방 8개는 120kg이에요. 하나를 노란 가방으로 바꾸면 20kg 늘어나요.','160kg까지 40kg이 더 필요해요. 20kg씩 늘리려면 몇 개를 바꾸면 될까요?']:['10초를 모두 느린 벨트로 이동하면 몇 m일까요?','느린 벨트로 10초 가면 10m예요. 그중 1초를 빠른 벨트로 바꾸면 1m 더 가요.','16m까지 6m가 더 필요해요. 빠른 벨트로 몇 초를 바꾸면 될까요?'];feedback(hints[Math.min(hint++,2)]);};
  controls.querySelector('.airport-reset').onclick=()=>{if(!checkRun()||won())return;running=false;paused=false;elapsed=0;s.x=0;s.y=0;board.classList.remove('airport-sending');sync();if(!bags)drawRoute();feedback('처음 값으로 돌아왔어요. 두 조건을 다시 살펴봐요.');persist();};
  function result(){running=false;paused=false;const q=M.inspect(id,s.x,s.y);if(q.ok){s.proof={x:s.x,y:s.y};tone(true);feedback(bags?'8개 · 160kg! 출발 기록을 복원하고 가방을 보냈어요.':'10초 · 16m! 두 조건이 함께 맞아 연결의 빛을 찾았어요.','good');persist();}else{tone(false);feedback((q.countOK?(bags?'개수는 맞았어요. ':'시간은 맞았어요. '):(bags?'개수를 다시 확인해요. ':'시간을 다시 확인해요. '))+(q.valueOK?(bags?'무게는 맞았어요.':'거리는 맞았어요.'):(bags?'무게도 160kg이어야 해요.':'거리도 16m이어야 해요.')),'bad');}sync();}
  confirm.onclick=()=>{if(dead||modal()||!checkRun())return;if(won()){next();return;}if(running){paused=!paused;sync();if(!bags)drawRoute();return;}const q=M.inspect(id,s.x,s.y);if(bags&&!q.ok){result();return;}if(!bags&&q.total===0){feedback('벨트를 이용할 시간을 먼저 정해 주세요.','bad');return;}elapsed=0;running=true;paused=false;sync();feedback(bags?'가방들이 같은 항공편을 향해 출발해요!':'빠른 벨트 다음 느린 벨트! 이동 시간과 거리를 지켜봐요.');};
  function drawRoute(){const total=s.x+s.y,sec=Math.min(elapsed,total),distance=2*Math.min(sec,s.x)+Math.max(0,sec-s.x),fastEnd=2*s.x;board.querySelector('.airport-fast').style.width=(fastEnd/32*100)+'%';const slow=board.querySelector('.airport-slow');slow.style.left=(fastEnd/32*100)+'%';slow.style.width=(s.y/32*100)+'%';board.querySelector('.airport-moving').style.left=(distance/32*100)+'%';board.querySelector('.airport-route-status').textContent=won()?'✓ 운송 완료 · 10초, 16m':elapsed>0?(sec.toFixed(1)+'초 · '+distance.toFixed(1)+'m  |  '+(sec>=total?'도착 기록 확인':paused?'잠시 멈춤':sec<s.x?'빠른 벨트 2m/초':'느린 벨트 1m/초')):'시간을 정하고 운송을 시작해요.';}
  function tick(time){if(dead)return;const dt=Math.min((time-last)/1000||0,.08);last=time;if(running&&!paused&&!modal()){elapsed+=dt;if(bags){const cargo=board.querySelector('.airport-cargo');cargo.style.transform='translateX('+Math.min(elapsed/2,1)*120+'%)';cargo.style.opacity=String(1-Math.min(elapsed/2,1));}else drawRoute();if(elapsed>=(bags?2:s.x+s.y)&&checkRun()){result();if(!bags)drawRoute();}}raf=requestAnimationFrame(tick);}
  sync();if(!bags){if(won())elapsed=s.x+s.y;drawRoute();}feedback(won()?'기록을 복원했어요. 여행을 이어가요.':bags?'＋로 가방을 싣고, 가방을 누르거나 −로 내려요. 8개와 160kg을 함께 맞춰요.':'두 벨트의 시간을 정해 10초 동안 16m를 이동해요.');raf=requestAnimationFrame(tick);
  return {pause(){if(running){paused=true;sync();if(!bags)drawRoute();}},destroy(){dead=true;cancelAnimationFrame(raf);game.classList.remove('airport-game');confirm.onclick=null;board.onclick=null;}};
 }
 root.AirportPlay={mount};
})(window);
